// Code generated by ent, DO NOT EDIT.

package unsealkeyslot

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the unsealkeyslot type in the database.
	Label = "unseal_key_slot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWrappedKey holds the string denoting the wrapped_key field in the database.
	FieldWrappedKey = "wrapped_key"
	// FieldServerKeyMaterial holds the string denoting the server_key_material field in the database.
	FieldServerKeyMaterial = "server_key_material"
	// Table holds the table name of the unsealkeyslot in the database.
	Table = "unseal_key_slots"
)

// Columns holds all SQL columns for unsealkeyslot fields.
var Columns = []string{
	FieldID,
	FieldWrappedKey,
	FieldServerKeyMaterial,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the UnsealKeySlot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
