// Code generated by ent, DO NOT EDIT.

package unsealkeyslot

import (
	"entgo.io/ent/dialect/sql"
	"github.com/rajabinekoo/sigryx/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldLTE(FieldID, id))
}

// WrappedKey applies equality check predicate on the "wrapped_key" field. It's identical to WrappedKeyEQ.
func WrappedKey(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldEQ(FieldWrappedKey, v))
}

// ServerKeyMaterial applies equality check predicate on the "server_key_material" field. It's identical to ServerKeyMaterialEQ.
func ServerKeyMaterial(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldEQ(FieldServerKeyMaterial, v))
}

// WrappedKeyEQ applies the EQ predicate on the "wrapped_key" field.
func WrappedKeyEQ(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldEQ(FieldWrappedKey, v))
}

// WrappedKeyNEQ applies the NEQ predicate on the "wrapped_key" field.
func WrappedKeyNEQ(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldNEQ(FieldWrappedKey, v))
}

// WrappedKeyIn applies the In predicate on the "wrapped_key" field.
func WrappedKeyIn(vs ...[]byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldIn(FieldWrappedKey, vs...))
}

// WrappedKeyNotIn applies the NotIn predicate on the "wrapped_key" field.
func WrappedKeyNotIn(vs ...[]byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldNotIn(FieldWrappedKey, vs...))
}

// WrappedKeyGT applies the GT predicate on the "wrapped_key" field.
func WrappedKeyGT(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldGT(FieldWrappedKey, v))
}

// WrappedKeyGTE applies the GTE predicate on the "wrapped_key" field.
func WrappedKeyGTE(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldGTE(FieldWrappedKey, v))
}

// WrappedKeyLT applies the LT predicate on the "wrapped_key" field.
func WrappedKeyLT(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldLT(FieldWrappedKey, v))
}

// WrappedKeyLTE applies the LTE predicate on the "wrapped_key" field.
func WrappedKeyLTE(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldLTE(FieldWrappedKey, v))
}

// ServerKeyMaterialEQ applies the EQ predicate on the "server_key_material" field.
func ServerKeyMaterialEQ(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldEQ(FieldServerKeyMaterial, v))
}

// ServerKeyMaterialNEQ applies the NEQ predicate on the "server_key_material" field.
func ServerKeyMaterialNEQ(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldNEQ(FieldServerKeyMaterial, v))
}

// ServerKeyMaterialIn applies the In predicate on the "server_key_material" field.
func ServerKeyMaterialIn(vs ...[]byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldIn(FieldServerKeyMaterial, vs...))
}

// ServerKeyMaterialNotIn applies the NotIn predicate on the "server_key_material" field.
func ServerKeyMaterialNotIn(vs ...[]byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldNotIn(FieldServerKeyMaterial, vs...))
}

// ServerKeyMaterialGT applies the GT predicate on the "server_key_material" field.
func ServerKeyMaterialGT(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldGT(FieldServerKeyMaterial, v))
}

// ServerKeyMaterialGTE applies the GTE predicate on the "server_key_material" field.
func ServerKeyMaterialGTE(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldGTE(FieldServerKeyMaterial, v))
}

// ServerKeyMaterialLT applies the LT predicate on the "server_key_material" field.
func ServerKeyMaterialLT(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldLT(FieldServerKeyMaterial, v))
}

// ServerKeyMaterialLTE applies the LTE predicate on the "server_key_material" field.
func ServerKeyMaterialLTE(v []byte) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.FieldLTE(FieldServerKeyMaterial, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UnsealKeySlot) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UnsealKeySlot) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UnsealKeySlot) predicate.UnsealKeySlot {
	return predicate.UnsealKeySlot(sql.NotPredicates(p))
}
