run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - gofmt
    - goimports
    - misspell
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  goimports:
    local-prefixes: crypto_payment
  revive:
    rules:
      - name: var-naming
      - name: exported
        arguments: ["disableStutteringCheck"]
      - name: context-as-argument
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: superfluous-else
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: unused-parameter

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
  max-issues-per-linter: 0
  max-same-issues: 0
