package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

type Wallet struct {
	ent.Schema
}

func (Wallet) Fields() []ent.Field {
	return []ent.Field{
		// Application-generated UUIDv7.
		field.String("id").
			SchemaType(map[string]string{
				dialect.Postgres: "uuid",
			}).
			Immutable(),

		// HD root from which this wallet was derived.
		field.String("key_root_id").
			SchemaType(map[string]string{
				dialect.Postgres: "uuid",
			}).
			Immutable(),

		// Blockchain adapter that defines derivation/address semantics.
		//
		// Examples:
		// evm
		// bitcoin
		// solana
		field.String("adapter").
			NotEmpty().
			Immutable(),

		// Exact deterministic derivation path.
		//
		// Example:
		// m/44'/60'/0'/0/15
		field.String("derivation_path").
			NotEmpty().
			Immutable(),

		// Canonical serialized public key generated from the
		// derived private key.
		field.Bytes("public_key").
			Immutable(),

		// Canonical blockchain address generated by the adapter.
		field.String("address").
			NotEmpty().
			Immutable(),
	}
}

func (Wallet) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("key_root", KeyRoot.Type).
			Ref("wallets").
			Field("key_root_id").
			Unique().
			Required().
			Immutable(),
	}
}

func (Wallet) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields(
			"key_root_id",
			"adapter",
			"derivation_path",
		).
			Unique(),

		index.Fields(
			"adapter",
			"address",
		).
			Unique(),
	}
}

func (Wallet) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Checks(map[string]string{
			"wallet_public_key_not_empty": "octet_length(public_key) > 0",
		}),
	}
}
