// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// KeyRootsColumns holds the columns for the "key_roots" table.
	KeyRootsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "derivation_scheme", Type: field.TypeString},
		{Name: "sealed_seed", Type: field.TypeBytes},
	}
	// KeyRootsTable holds the schema information for the "key_roots" table.
	KeyRootsTable = &schema.Table{
		Name:       "key_roots",
		Columns:    KeyRootsColumns,
		PrimaryKey: []*schema.Column{KeyRootsColumns[0]},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "permissions", Type: field.TypeJSON},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// ServiceAccountsColumns holds the columns for the "service_accounts" table.
	ServiceAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "client_id", Type: field.TypeString, Unique: true},
		{Name: "client_secret_hash", Type: field.TypeBytes},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "allowed_cidrs", Type: field.TypeJSON},
		{Name: "role_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// ServiceAccountsTable holds the schema information for the "service_accounts" table.
	ServiceAccountsTable = &schema.Table{
		Name:       "service_accounts",
		Columns:    ServiceAccountsColumns,
		PrimaryKey: []*schema.Column{ServiceAccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "service_accounts_roles_service_accounts",
				Columns:    []*schema.Column{ServiceAccountsColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "refresh_token_hash", Type: field.TypeBytes},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "session_refresh_token_hash",
				Unique:  true,
				Columns: []*schema.Column{SessionsColumns[1]},
			},
			{
				Name:    "session_user_id",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[4]},
			},
		},
	}
	// UnsealKeySlotsColumns holds the columns for the "unseal_key_slots" table.
	UnsealKeySlotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "wrapped_key", Type: field.TypeBytes},
		{Name: "server_key_material", Type: field.TypeBytes},
	}
	// UnsealKeySlotsTable holds the schema information for the "unseal_key_slots" table.
	UnsealKeySlotsTable = &schema.Table{
		Name:       "unseal_key_slots",
		Columns:    UnsealKeySlotsColumns,
		PrimaryKey: []*schema.Column{UnsealKeySlotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "unsealkeyslot_wrapped_key",
				Unique:  true,
				Columns: []*schema.Column{UnsealKeySlotsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "is_root_admin", Type: field.TypeBool, Default: false},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "allowed_cidrs", Type: field.TypeJSON},
		{Name: "role_id", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_roles_users",
				Columns:    []*schema.Column{UsersColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_is_root_admin",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Where: "is_root_admin = true",
				},
			},
		},
	}
	// WalletsColumns holds the columns for the "wallets" table.
	WalletsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "user_id", Type: field.TypeString},
		{Name: "adapter", Type: field.TypeString},
		{Name: "derivation_path", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeBytes},
		{Name: "address", Type: field.TypeString},
		{Name: "key_root_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// WalletsTable holds the schema information for the "wallets" table.
	WalletsTable = &schema.Table{
		Name:       "wallets",
		Columns:    WalletsColumns,
		PrimaryKey: []*schema.Column{WalletsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wallets_key_roots_wallets",
				Columns:    []*schema.Column{WalletsColumns[6]},
				RefColumns: []*schema.Column{KeyRootsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "wallet_key_root_id_adapter_user_id",
				Unique:  true,
				Columns: []*schema.Column{WalletsColumns[6], WalletsColumns[2], WalletsColumns[1]},
			},
			{
				Name:    "wallet_key_root_id_adapter_derivation_path",
				Unique:  true,
				Columns: []*schema.Column{WalletsColumns[6], WalletsColumns[2], WalletsColumns[3]},
			},
			{
				Name:    "wallet_adapter_address",
				Unique:  true,
				Columns: []*schema.Column{WalletsColumns[2], WalletsColumns[5]},
			},
		},
	}
	// WalletCountersColumns holds the columns for the "wallet_counters" table.
	WalletCountersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "adapter", Type: field.TypeString},
		{Name: "next_index", Type: field.TypeInt64, Default: 0},
		{Name: "key_root_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// WalletCountersTable holds the schema information for the "wallet_counters" table.
	WalletCountersTable = &schema.Table{
		Name:       "wallet_counters",
		Columns:    WalletCountersColumns,
		PrimaryKey: []*schema.Column{WalletCountersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wallet_counters_key_roots_wallet_counters",
				Columns:    []*schema.Column{WalletCountersColumns[3]},
				RefColumns: []*schema.Column{KeyRootsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "walletcounter_key_root_id_adapter",
				Unique:  true,
				Columns: []*schema.Column{WalletCountersColumns[3], WalletCountersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		KeyRootsTable,
		RolesTable,
		ServiceAccountsTable,
		SessionsTable,
		UnsealKeySlotsTable,
		UsersTable,
		WalletsTable,
		WalletCountersTable,
	}
)

func init() {
	KeyRootsTable.Annotation = &entsql.Annotation{}
	KeyRootsTable.Annotation.Checks = map[string]string{
		"key_root_sealed_seed_not_empty": "octet_length(sealed_seed) > 0",
	}
	ServiceAccountsTable.ForeignKeys[0].RefTable = RolesTable
	ServiceAccountsTable.Annotation = &entsql.Annotation{}
	ServiceAccountsTable.Annotation.Checks = map[string]string{
		"service_account_secret_hash_size": "octet_length(client_secret_hash) = 32",
	}
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	SessionsTable.Annotation = &entsql.Annotation{}
	SessionsTable.Annotation.Checks = map[string]string{
		"session_refresh_token_hash_size": "octet_length(refresh_token_hash) = 32",
	}
	UnsealKeySlotsTable.Annotation = &entsql.Annotation{}
	UnsealKeySlotsTable.Annotation.Checks = map[string]string{
		"unseal_server_key_material_size": "octet_length(server_key_material) = 32",
		"unseal_wrapped_key_not_empty":    "octet_length(wrapped_key) > 0",
	}
	UsersTable.ForeignKeys[0].RefTable = RolesTable
	UsersTable.Annotation = &entsql.Annotation{}
	UsersTable.Annotation.Checks = map[string]string{
		"user_root_role_consistency": "(is_root_admin = true AND role_id IS NULL) OR (is_root_admin = false AND role_id IS NOT NULL)",
	}
	WalletsTable.ForeignKeys[0].RefTable = KeyRootsTable
	WalletsTable.Annotation = &entsql.Annotation{}
	WalletsTable.Annotation.Checks = map[string]string{
		"wallet_public_key_not_empty": "octet_length(public_key) > 0",
	}
	WalletCountersTable.ForeignKeys[0].RefTable = KeyRootsTable
	WalletCountersTable.Annotation = &entsql.Annotation{}
	WalletCountersTable.Annotation.Checks = map[string]string{
		"wallet_counter_index_range": "next_index >= 0 AND next_index <= 2147483648",
	}
}
