// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rajabinekoo/sigryx/internal/ent/auditevent"
)

// AuditEventCreate is the builder for creating a AuditEvent entity.
type AuditEventCreate struct {
	config
	mutation *AuditEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *AuditEventCreate) SetOccurredAt(v time.Time) *AuditEventCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableOccurredAt(v *time.Time) *AuditEventCreate {
	if v != nil {
		_c.SetOccurredAt(*v)
	}
	return _c
}

// SetActorType sets the "actor_type" field.
func (_c *AuditEventCreate) SetActorType(v string) *AuditEventCreate {
	_c.mutation.SetActorType(v)
	return _c
}

// SetNillableActorType sets the "actor_type" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableActorType(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetActorType(*v)
	}
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *AuditEventCreate) SetActorID(v string) *AuditEventCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableActorID(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AuditEventCreate) SetSessionID(v string) *AuditEventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableSessionID(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AuditEventCreate) SetAction(v string) *AuditEventCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *AuditEventCreate) SetOutcome(v string) *AuditEventCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetSourceIP sets the "source_ip" field.
func (_c *AuditEventCreate) SetSourceIP(v string) *AuditEventCreate {
	_c.mutation.SetSourceIP(v)
	return _c
}

// SetNillableSourceIP sets the "source_ip" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableSourceIP(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetSourceIP(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *AuditEventCreate) SetRequestID(v string) *AuditEventCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableRequestID(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *AuditEventCreate) SetMethod(v string) *AuditEventCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableMethod(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *AuditEventCreate) SetPath(v string) *AuditEventCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillablePath(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *AuditEventCreate) SetStatusCode(v int) *AuditEventCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableStatusCode(v *int) *AuditEventCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetDetails sets the "details" field.
func (_c *AuditEventCreate) SetDetails(v map[string]interface{}) *AuditEventCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetRetentionClass sets the "retention_class" field.
func (_c *AuditEventCreate) SetRetentionClass(v string) *AuditEventCreate {
	_c.mutation.SetRetentionClass(v)
	return _c
}

// SetNillableRetentionClass sets the "retention_class" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableRetentionClass(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetRetentionClass(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuditEventCreate) SetID(v string) *AuditEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuditEventMutation object of the builder.
func (_c *AuditEventCreate) Mutation() *AuditEventMutation {
	return _c.mutation
}

// Save creates the AuditEvent in the database.
func (_c *AuditEventCreate) Save(ctx context.Context) (*AuditEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditEventCreate) SaveX(ctx context.Context) *AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditEventCreate) defaults() {
	if _, ok := _c.mutation.OccurredAt(); !ok {
		v := auditevent.DefaultOccurredAt()
		_c.mutation.SetOccurredAt(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := auditevent.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.Details(); !ok {
		v := auditevent.DefaultDetails
		_c.mutation.SetDetails(v)
	}
	if _, ok := _c.mutation.RetentionClass(); !ok {
		v := auditevent.DefaultRetentionClass
		_c.mutation.SetRetentionClass(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditEventCreate) check() error {
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "AuditEvent.occurred_at"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AuditEvent.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := auditevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditEvent.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "AuditEvent.outcome"`)}
	}
	if v, ok := _c.mutation.Outcome(); ok {
		if err := auditevent.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "AuditEvent.outcome": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "AuditEvent.status_code"`)}
	}
	if _, ok := _c.mutation.Details(); !ok {
		return &ValidationError{Name: "details", err: errors.New(`ent: missing required field "AuditEvent.details"`)}
	}
	if _, ok := _c.mutation.RetentionClass(); !ok {
		return &ValidationError{Name: "retention_class", err: errors.New(`ent: missing required field "AuditEvent.retention_class"`)}
	}
	return nil
}

func (_c *AuditEventCreate) sqlSave(ctx context.Context) (*AuditEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuditEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditEventCreate) createSpec() (*AuditEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditevent.Table, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(auditevent.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.ActorType(); ok {
		_spec.SetField(auditevent.FieldActorType, field.TypeString, value)
		_node.ActorType = &value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(auditevent.FieldActorID, field.TypeString, value)
		_node.ActorID = &value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(auditevent.FieldSessionID, field.TypeString, value)
		_node.SessionID = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(auditevent.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(auditevent.FieldOutcome, field.TypeString, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.SourceIP(); ok {
		_spec.SetField(auditevent.FieldSourceIP, field.TypeString, value)
		_node.SourceIP = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(auditevent.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(auditevent.FieldMethod, field.TypeString, value)
		_node.Method = &value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(auditevent.FieldPath, field.TypeString, value)
		_node.Path = &value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(auditevent.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(auditevent.FieldDetails, field.TypeJSON, value)
		_node.Details = value
	}
	if value, ok := _c.mutation.RetentionClass(); ok {
		_spec.SetField(auditevent.FieldRetentionClass, field.TypeString, value)
		_node.RetentionClass = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditEvent.Create().
//		SetOccurredAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditEventUpsert) {
//			SetOccurredAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditEventCreate) OnConflict(opts ...sql.ConflictOption) *AuditEventUpsertOne {
	_c.conflict = opts
	return &AuditEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditEventCreate) OnConflictColumns(columns ...string) *AuditEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditEventUpsertOne{
		create: _c,
	}
}

type (
	// AuditEventUpsertOne is the builder for "upsert"-ing
	//  one AuditEvent node.
	AuditEventUpsertOne struct {
		create *AuditEventCreate
	}

	// AuditEventUpsert is the "OnConflict" setter.
	AuditEventUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditEventUpsertOne) UpdateNewValues() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(auditevent.FieldID)
		}
		if _, exists := u.create.mutation.OccurredAt(); exists {
			s.SetIgnore(auditevent.FieldOccurredAt)
		}
		if _, exists := u.create.mutation.ActorType(); exists {
			s.SetIgnore(auditevent.FieldActorType)
		}
		if _, exists := u.create.mutation.ActorID(); exists {
			s.SetIgnore(auditevent.FieldActorID)
		}
		if _, exists := u.create.mutation.SessionID(); exists {
			s.SetIgnore(auditevent.FieldSessionID)
		}
		if _, exists := u.create.mutation.Action(); exists {
			s.SetIgnore(auditevent.FieldAction)
		}
		if _, exists := u.create.mutation.Outcome(); exists {
			s.SetIgnore(auditevent.FieldOutcome)
		}
		if _, exists := u.create.mutation.SourceIP(); exists {
			s.SetIgnore(auditevent.FieldSourceIP)
		}
		if _, exists := u.create.mutation.RequestID(); exists {
			s.SetIgnore(auditevent.FieldRequestID)
		}
		if _, exists := u.create.mutation.Method(); exists {
			s.SetIgnore(auditevent.FieldMethod)
		}
		if _, exists := u.create.mutation.Path(); exists {
			s.SetIgnore(auditevent.FieldPath)
		}
		if _, exists := u.create.mutation.StatusCode(); exists {
			s.SetIgnore(auditevent.FieldStatusCode)
		}
		if _, exists := u.create.mutation.Details(); exists {
			s.SetIgnore(auditevent.FieldDetails)
		}
		if _, exists := u.create.mutation.RetentionClass(); exists {
			s.SetIgnore(auditevent.FieldRetentionClass)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuditEventUpsertOne) Ignore() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditEventUpsertOne) DoNothing() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditEventCreate.OnConflict
// documentation for more info.
func (u *AuditEventUpsertOne) Update(set func(*AuditEventUpsert)) *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuditEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuditEventUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuditEventUpsertOne.ID is not supported by MySQL driver. Use AuditEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuditEventUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuditEventCreateBulk is the builder for creating many AuditEvent entities in bulk.
type AuditEventCreateBulk struct {
	config
	err      error
	builders []*AuditEventCreate
	conflict []sql.ConflictOption
}

// Save creates the AuditEvent entities in the database.
func (_c *AuditEventCreateBulk) Save(ctx context.Context) ([]*AuditEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditEventCreateBulk) SaveX(ctx context.Context) []*AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditEventUpsert) {
//			SetOccurredAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuditEventUpsertBulk {
	_c.conflict = opts
	return &AuditEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditEventCreateBulk) OnConflictColumns(columns ...string) *AuditEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditEventUpsertBulk{
		create: _c,
	}
}

// AuditEventUpsertBulk is the builder for "upsert"-ing
// a bulk of AuditEvent nodes.
type AuditEventUpsertBulk struct {
	create *AuditEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditEventUpsertBulk) UpdateNewValues() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(auditevent.FieldID)
			}
			if _, exists := b.mutation.OccurredAt(); exists {
				s.SetIgnore(auditevent.FieldOccurredAt)
			}
			if _, exists := b.mutation.ActorType(); exists {
				s.SetIgnore(auditevent.FieldActorType)
			}
			if _, exists := b.mutation.ActorID(); exists {
				s.SetIgnore(auditevent.FieldActorID)
			}
			if _, exists := b.mutation.SessionID(); exists {
				s.SetIgnore(auditevent.FieldSessionID)
			}
			if _, exists := b.mutation.Action(); exists {
				s.SetIgnore(auditevent.FieldAction)
			}
			if _, exists := b.mutation.Outcome(); exists {
				s.SetIgnore(auditevent.FieldOutcome)
			}
			if _, exists := b.mutation.SourceIP(); exists {
				s.SetIgnore(auditevent.FieldSourceIP)
			}
			if _, exists := b.mutation.RequestID(); exists {
				s.SetIgnore(auditevent.FieldRequestID)
			}
			if _, exists := b.mutation.Method(); exists {
				s.SetIgnore(auditevent.FieldMethod)
			}
			if _, exists := b.mutation.Path(); exists {
				s.SetIgnore(auditevent.FieldPath)
			}
			if _, exists := b.mutation.StatusCode(); exists {
				s.SetIgnore(auditevent.FieldStatusCode)
			}
			if _, exists := b.mutation.Details(); exists {
				s.SetIgnore(auditevent.FieldDetails)
			}
			if _, exists := b.mutation.RetentionClass(); exists {
				s.SetIgnore(auditevent.FieldRetentionClass)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuditEventUpsertBulk) Ignore() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditEventUpsertBulk) DoNothing() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditEventCreateBulk.OnConflict
// documentation for more info.
func (u *AuditEventUpsertBulk) Update(set func(*AuditEventUpsert)) *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuditEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuditEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
