// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/rajabinekoo/sigryx/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rajabinekoo/sigryx/internal/ent/auditevent"
	"github.com/rajabinekoo/sigryx/internal/ent/keyroot"
	"github.com/rajabinekoo/sigryx/internal/ent/role"
	"github.com/rajabinekoo/sigryx/internal/ent/serviceaccount"
	"github.com/rajabinekoo/sigryx/internal/ent/session"
	"github.com/rajabinekoo/sigryx/internal/ent/signingrecord"
	"github.com/rajabinekoo/sigryx/internal/ent/unsealkeyslot"
	"github.com/rajabinekoo/sigryx/internal/ent/user"
	"github.com/rajabinekoo/sigryx/internal/ent/wallet"
	"github.com/rajabinekoo/sigryx/internal/ent/walletcounter"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AuditEvent is the client for interacting with the AuditEvent builders.
	AuditEvent *AuditEventClient
	// KeyRoot is the client for interacting with the KeyRoot builders.
	KeyRoot *KeyRootClient
	// Role is the client for interacting with the Role builders.
	Role *RoleClient
	// ServiceAccount is the client for interacting with the ServiceAccount builders.
	ServiceAccount *ServiceAccountClient
	// Session is the client for interacting with the Session builders.
	Session *SessionClient
	// SigningRecord is the client for interacting with the SigningRecord builders.
	SigningRecord *SigningRecordClient
	// UnsealKeySlot is the client for interacting with the UnsealKeySlot builders.
	UnsealKeySlot *UnsealKeySlotClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// Wallet is the client for interacting with the Wallet builders.
	Wallet *WalletClient
	// WalletCounter is the client for interacting with the WalletCounter builders.
	WalletCounter *WalletCounterClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AuditEvent = NewAuditEventClient(c.config)
	c.KeyRoot = NewKeyRootClient(c.config)
	c.Role = NewRoleClient(c.config)
	c.ServiceAccount = NewServiceAccountClient(c.config)
	c.Session = NewSessionClient(c.config)
	c.SigningRecord = NewSigningRecordClient(c.config)
	c.UnsealKeySlot = NewUnsealKeySlotClient(c.config)
	c.User = NewUserClient(c.config)
	c.Wallet = NewWalletClient(c.config)
	c.WalletCounter = NewWalletCounterClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		AuditEvent:     NewAuditEventClient(cfg),
		KeyRoot:        NewKeyRootClient(cfg),
		Role:           NewRoleClient(cfg),
		ServiceAccount: NewServiceAccountClient(cfg),
		Session:        NewSessionClient(cfg),
		SigningRecord:  NewSigningRecordClient(cfg),
		UnsealKeySlot:  NewUnsealKeySlotClient(cfg),
		User:           NewUserClient(cfg),
		Wallet:         NewWalletClient(cfg),
		WalletCounter:  NewWalletCounterClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		AuditEvent:     NewAuditEventClient(cfg),
		KeyRoot:        NewKeyRootClient(cfg),
		Role:           NewRoleClient(cfg),
		ServiceAccount: NewServiceAccountClient(cfg),
		Session:        NewSessionClient(cfg),
		SigningRecord:  NewSigningRecordClient(cfg),
		UnsealKeySlot:  NewUnsealKeySlotClient(cfg),
		User:           NewUserClient(cfg),
		Wallet:         NewWalletClient(cfg),
		WalletCounter:  NewWalletCounterClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AuditEvent.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AuditEvent, c.KeyRoot, c.Role, c.ServiceAccount, c.Session, c.SigningRecord,
		c.UnsealKeySlot, c.User, c.Wallet, c.WalletCounter,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AuditEvent, c.KeyRoot, c.Role, c.ServiceAccount, c.Session, c.SigningRecord,
		c.UnsealKeySlot, c.User, c.Wallet, c.WalletCounter,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AuditEventMutation:
		return c.AuditEvent.mutate(ctx, m)
	case *KeyRootMutation:
		return c.KeyRoot.mutate(ctx, m)
	case *RoleMutation:
		return c.Role.mutate(ctx, m)
	case *ServiceAccountMutation:
		return c.ServiceAccount.mutate(ctx, m)
	case *SessionMutation:
		return c.Session.mutate(ctx, m)
	case *SigningRecordMutation:
		return c.SigningRecord.mutate(ctx, m)
	case *UnsealKeySlotMutation:
		return c.UnsealKeySlot.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *WalletMutation:
		return c.Wallet.mutate(ctx, m)
	case *WalletCounterMutation:
		return c.WalletCounter.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AuditEventClient is a client for the AuditEvent schema.
type AuditEventClient struct {
	config
}

// NewAuditEventClient returns a client for the AuditEvent from the given config.
func NewAuditEventClient(c config) *AuditEventClient {
	return &AuditEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditevent.Hooks(f(g(h())))`.
func (c *AuditEventClient) Use(hooks ...Hook) {
	c.hooks.AuditEvent = append(c.hooks.AuditEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditevent.Intercept(f(g(h())))`.
func (c *AuditEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditEvent = append(c.inters.AuditEvent, interceptors...)
}

// Create returns a builder for creating a AuditEvent entity.
func (c *AuditEventClient) Create() *AuditEventCreate {
	mutation := newAuditEventMutation(c.config, OpCreate)
	return &AuditEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditEvent entities.
func (c *AuditEventClient) CreateBulk(builders ...*AuditEventCreate) *AuditEventCreateBulk {
	return &AuditEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditEventClient) MapCreateBulk(slice any, setFunc func(*AuditEventCreate, int)) *AuditEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditEventCreateBulk{err: fmt.Errorf("calling to AuditEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditEvent.
func (c *AuditEventClient) Update() *AuditEventUpdate {
	mutation := newAuditEventMutation(c.config, OpUpdate)
	return &AuditEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditEventClient) UpdateOne(_m *AuditEvent) *AuditEventUpdateOne {
	mutation := newAuditEventMutation(c.config, OpUpdateOne, withAuditEvent(_m))
	return &AuditEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditEventClient) UpdateOneID(id string) *AuditEventUpdateOne {
	mutation := newAuditEventMutation(c.config, OpUpdateOne, withAuditEventID(id))
	return &AuditEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditEvent.
func (c *AuditEventClient) Delete() *AuditEventDelete {
	mutation := newAuditEventMutation(c.config, OpDelete)
	return &AuditEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditEventClient) DeleteOne(_m *AuditEvent) *AuditEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditEventClient) DeleteOneID(id string) *AuditEventDeleteOne {
	builder := c.Delete().Where(auditevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditEventDeleteOne{builder}
}

// Query returns a query builder for AuditEvent.
func (c *AuditEventClient) Query() *AuditEventQuery {
	return &AuditEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditEvent entity by its id.
func (c *AuditEventClient) Get(ctx context.Context, id string) (*AuditEvent, error) {
	return c.Query().Where(auditevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditEventClient) GetX(ctx context.Context, id string) *AuditEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuditEventClient) Hooks() []Hook {
	return c.hooks.AuditEvent
}

// Interceptors returns the client interceptors.
func (c *AuditEventClient) Interceptors() []Interceptor {
	return c.inters.AuditEvent
}

func (c *AuditEventClient) mutate(ctx context.Context, m *AuditEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditEvent mutation op: %q", m.Op())
	}
}

// KeyRootClient is a client for the KeyRoot schema.
type KeyRootClient struct {
	config
}

// NewKeyRootClient returns a client for the KeyRoot from the given config.
func NewKeyRootClient(c config) *KeyRootClient {
	return &KeyRootClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `keyroot.Hooks(f(g(h())))`.
func (c *KeyRootClient) Use(hooks ...Hook) {
	c.hooks.KeyRoot = append(c.hooks.KeyRoot, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `keyroot.Intercept(f(g(h())))`.
func (c *KeyRootClient) Intercept(interceptors ...Interceptor) {
	c.inters.KeyRoot = append(c.inters.KeyRoot, interceptors...)
}

// Create returns a builder for creating a KeyRoot entity.
func (c *KeyRootClient) Create() *KeyRootCreate {
	mutation := newKeyRootMutation(c.config, OpCreate)
	return &KeyRootCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of KeyRoot entities.
func (c *KeyRootClient) CreateBulk(builders ...*KeyRootCreate) *KeyRootCreateBulk {
	return &KeyRootCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *KeyRootClient) MapCreateBulk(slice any, setFunc func(*KeyRootCreate, int)) *KeyRootCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &KeyRootCreateBulk{err: fmt.Errorf("calling to KeyRootClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*KeyRootCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &KeyRootCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for KeyRoot.
func (c *KeyRootClient) Update() *KeyRootUpdate {
	mutation := newKeyRootMutation(c.config, OpUpdate)
	return &KeyRootUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *KeyRootClient) UpdateOne(_m *KeyRoot) *KeyRootUpdateOne {
	mutation := newKeyRootMutation(c.config, OpUpdateOne, withKeyRoot(_m))
	return &KeyRootUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *KeyRootClient) UpdateOneID(id string) *KeyRootUpdateOne {
	mutation := newKeyRootMutation(c.config, OpUpdateOne, withKeyRootID(id))
	return &KeyRootUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for KeyRoot.
func (c *KeyRootClient) Delete() *KeyRootDelete {
	mutation := newKeyRootMutation(c.config, OpDelete)
	return &KeyRootDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *KeyRootClient) DeleteOne(_m *KeyRoot) *KeyRootDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *KeyRootClient) DeleteOneID(id string) *KeyRootDeleteOne {
	builder := c.Delete().Where(keyroot.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &KeyRootDeleteOne{builder}
}

// Query returns a query builder for KeyRoot.
func (c *KeyRootClient) Query() *KeyRootQuery {
	return &KeyRootQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeKeyRoot},
		inters: c.Interceptors(),
	}
}

// Get returns a KeyRoot entity by its id.
func (c *KeyRootClient) Get(ctx context.Context, id string) (*KeyRoot, error) {
	return c.Query().Where(keyroot.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *KeyRootClient) GetX(ctx context.Context, id string) *KeyRoot {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryWallets queries the wallets edge of a KeyRoot.
func (c *KeyRootClient) QueryWallets(_m *KeyRoot) *WalletQuery {
	query := (&WalletClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(keyroot.Table, keyroot.FieldID, id),
			sqlgraph.To(wallet.Table, wallet.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, keyroot.WalletsTable, keyroot.WalletsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryWalletCounters queries the wallet_counters edge of a KeyRoot.
func (c *KeyRootClient) QueryWalletCounters(_m *KeyRoot) *WalletCounterQuery {
	query := (&WalletCounterClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(keyroot.Table, keyroot.FieldID, id),
			sqlgraph.To(walletcounter.Table, walletcounter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, keyroot.WalletCountersTable, keyroot.WalletCountersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *KeyRootClient) Hooks() []Hook {
	return c.hooks.KeyRoot
}

// Interceptors returns the client interceptors.
func (c *KeyRootClient) Interceptors() []Interceptor {
	return c.inters.KeyRoot
}

func (c *KeyRootClient) mutate(ctx context.Context, m *KeyRootMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&KeyRootCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&KeyRootUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&KeyRootUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&KeyRootDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown KeyRoot mutation op: %q", m.Op())
	}
}

// RoleClient is a client for the Role schema.
type RoleClient struct {
	config
}

// NewRoleClient returns a client for the Role from the given config.
func NewRoleClient(c config) *RoleClient {
	return &RoleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `role.Hooks(f(g(h())))`.
func (c *RoleClient) Use(hooks ...Hook) {
	c.hooks.Role = append(c.hooks.Role, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `role.Intercept(f(g(h())))`.
func (c *RoleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Role = append(c.inters.Role, interceptors...)
}

// Create returns a builder for creating a Role entity.
func (c *RoleClient) Create() *RoleCreate {
	mutation := newRoleMutation(c.config, OpCreate)
	return &RoleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Role entities.
func (c *RoleClient) CreateBulk(builders ...*RoleCreate) *RoleCreateBulk {
	return &RoleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RoleClient) MapCreateBulk(slice any, setFunc func(*RoleCreate, int)) *RoleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RoleCreateBulk{err: fmt.Errorf("calling to RoleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RoleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RoleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Role.
func (c *RoleClient) Update() *RoleUpdate {
	mutation := newRoleMutation(c.config, OpUpdate)
	return &RoleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RoleClient) UpdateOne(_m *Role) *RoleUpdateOne {
	mutation := newRoleMutation(c.config, OpUpdateOne, withRole(_m))
	return &RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RoleClient) UpdateOneID(id string) *RoleUpdateOne {
	mutation := newRoleMutation(c.config, OpUpdateOne, withRoleID(id))
	return &RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Role.
func (c *RoleClient) Delete() *RoleDelete {
	mutation := newRoleMutation(c.config, OpDelete)
	return &RoleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RoleClient) DeleteOne(_m *Role) *RoleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RoleClient) DeleteOneID(id string) *RoleDeleteOne {
	builder := c.Delete().Where(role.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RoleDeleteOne{builder}
}

// Query returns a query builder for Role.
func (c *RoleClient) Query() *RoleQuery {
	return &RoleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRole},
		inters: c.Interceptors(),
	}
}

// Get returns a Role entity by its id.
func (c *RoleClient) Get(ctx context.Context, id string) (*Role, error) {
	return c.Query().Where(role.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RoleClient) GetX(ctx context.Context, id string) *Role {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a Role.
func (c *RoleClient) QueryUsers(_m *Role) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(role.Table, role.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, role.UsersTable, role.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryServiceAccounts queries the service_accounts edge of a Role.
func (c *RoleClient) QueryServiceAccounts(_m *Role) *ServiceAccountQuery {
	query := (&ServiceAccountClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(role.Table, role.FieldID, id),
			sqlgraph.To(serviceaccount.Table, serviceaccount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, role.ServiceAccountsTable, role.ServiceAccountsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RoleClient) Hooks() []Hook {
	return c.hooks.Role
}

// Interceptors returns the client interceptors.
func (c *RoleClient) Interceptors() []Interceptor {
	return c.inters.Role
}

func (c *RoleClient) mutate(ctx context.Context, m *RoleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RoleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RoleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RoleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Role mutation op: %q", m.Op())
	}
}

// ServiceAccountClient is a client for the ServiceAccount schema.
type ServiceAccountClient struct {
	config
}

// NewServiceAccountClient returns a client for the ServiceAccount from the given config.
func NewServiceAccountClient(c config) *ServiceAccountClient {
	return &ServiceAccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `serviceaccount.Hooks(f(g(h())))`.
func (c *ServiceAccountClient) Use(hooks ...Hook) {
	c.hooks.ServiceAccount = append(c.hooks.ServiceAccount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `serviceaccount.Intercept(f(g(h())))`.
func (c *ServiceAccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.ServiceAccount = append(c.inters.ServiceAccount, interceptors...)
}

// Create returns a builder for creating a ServiceAccount entity.
func (c *ServiceAccountClient) Create() *ServiceAccountCreate {
	mutation := newServiceAccountMutation(c.config, OpCreate)
	return &ServiceAccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ServiceAccount entities.
func (c *ServiceAccountClient) CreateBulk(builders ...*ServiceAccountCreate) *ServiceAccountCreateBulk {
	return &ServiceAccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ServiceAccountClient) MapCreateBulk(slice any, setFunc func(*ServiceAccountCreate, int)) *ServiceAccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ServiceAccountCreateBulk{err: fmt.Errorf("calling to ServiceAccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ServiceAccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ServiceAccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ServiceAccount.
func (c *ServiceAccountClient) Update() *ServiceAccountUpdate {
	mutation := newServiceAccountMutation(c.config, OpUpdate)
	return &ServiceAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ServiceAccountClient) UpdateOne(_m *ServiceAccount) *ServiceAccountUpdateOne {
	mutation := newServiceAccountMutation(c.config, OpUpdateOne, withServiceAccount(_m))
	return &ServiceAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ServiceAccountClient) UpdateOneID(id string) *ServiceAccountUpdateOne {
	mutation := newServiceAccountMutation(c.config, OpUpdateOne, withServiceAccountID(id))
	return &ServiceAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ServiceAccount.
func (c *ServiceAccountClient) Delete() *ServiceAccountDelete {
	mutation := newServiceAccountMutation(c.config, OpDelete)
	return &ServiceAccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ServiceAccountClient) DeleteOne(_m *ServiceAccount) *ServiceAccountDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ServiceAccountClient) DeleteOneID(id string) *ServiceAccountDeleteOne {
	builder := c.Delete().Where(serviceaccount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ServiceAccountDeleteOne{builder}
}

// Query returns a query builder for ServiceAccount.
func (c *ServiceAccountClient) Query() *ServiceAccountQuery {
	return &ServiceAccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeServiceAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a ServiceAccount entity by its id.
func (c *ServiceAccountClient) Get(ctx context.Context, id string) (*ServiceAccount, error) {
	return c.Query().Where(serviceaccount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ServiceAccountClient) GetX(ctx context.Context, id string) *ServiceAccount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRole queries the role edge of a ServiceAccount.
func (c *ServiceAccountClient) QueryRole(_m *ServiceAccount) *RoleQuery {
	query := (&RoleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(serviceaccount.Table, serviceaccount.FieldID, id),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, serviceaccount.RoleTable, serviceaccount.RoleColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ServiceAccountClient) Hooks() []Hook {
	return c.hooks.ServiceAccount
}

// Interceptors returns the client interceptors.
func (c *ServiceAccountClient) Interceptors() []Interceptor {
	return c.inters.ServiceAccount
}

func (c *ServiceAccountClient) mutate(ctx context.Context, m *ServiceAccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ServiceAccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ServiceAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ServiceAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ServiceAccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ServiceAccount mutation op: %q", m.Op())
	}
}

// SessionClient is a client for the Session schema.
type SessionClient struct {
	config
}

// NewSessionClient returns a client for the Session from the given config.
func NewSessionClient(c config) *SessionClient {
	return &SessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `session.Hooks(f(g(h())))`.
func (c *SessionClient) Use(hooks ...Hook) {
	c.hooks.Session = append(c.hooks.Session, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `session.Intercept(f(g(h())))`.
func (c *SessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Session = append(c.inters.Session, interceptors...)
}

// Create returns a builder for creating a Session entity.
func (c *SessionClient) Create() *SessionCreate {
	mutation := newSessionMutation(c.config, OpCreate)
	return &SessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Session entities.
func (c *SessionClient) CreateBulk(builders ...*SessionCreate) *SessionCreateBulk {
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionClient) MapCreateBulk(slice any, setFunc func(*SessionCreate, int)) *SessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionCreateBulk{err: fmt.Errorf("calling to SessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Session.
func (c *SessionClient) Update() *SessionUpdate {
	mutation := newSessionMutation(c.config, OpUpdate)
	return &SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionClient) UpdateOne(_m *Session) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSession(_m))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionClient) UpdateOneID(id string) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSessionID(id))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Session.
func (c *SessionClient) Delete() *SessionDelete {
	mutation := newSessionMutation(c.config, OpDelete)
	return &SessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionClient) DeleteOne(_m *Session) *SessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionClient) DeleteOneID(id string) *SessionDeleteOne {
	builder := c.Delete().Where(session.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionDeleteOne{builder}
}

// Query returns a query builder for Session.
func (c *SessionClient) Query() *SessionQuery {
	return &SessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSession},
		inters: c.Interceptors(),
	}
}

// Get returns a Session entity by its id.
func (c *SessionClient) Get(ctx context.Context, id string) (*Session, error) {
	return c.Query().Where(session.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionClient) GetX(ctx context.Context, id string) *Session {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Session.
func (c *SessionClient) QueryUser(_m *Session) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, session.UserTable, session.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionClient) Hooks() []Hook {
	return c.hooks.Session
}

// Interceptors returns the client interceptors.
func (c *SessionClient) Interceptors() []Interceptor {
	return c.inters.Session
}

func (c *SessionClient) mutate(ctx context.Context, m *SessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Session mutation op: %q", m.Op())
	}
}

// SigningRecordClient is a client for the SigningRecord schema.
type SigningRecordClient struct {
	config
}

// NewSigningRecordClient returns a client for the SigningRecord from the given config.
func NewSigningRecordClient(c config) *SigningRecordClient {
	return &SigningRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `signingrecord.Hooks(f(g(h())))`.
func (c *SigningRecordClient) Use(hooks ...Hook) {
	c.hooks.SigningRecord = append(c.hooks.SigningRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `signingrecord.Intercept(f(g(h())))`.
func (c *SigningRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.SigningRecord = append(c.inters.SigningRecord, interceptors...)
}

// Create returns a builder for creating a SigningRecord entity.
func (c *SigningRecordClient) Create() *SigningRecordCreate {
	mutation := newSigningRecordMutation(c.config, OpCreate)
	return &SigningRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SigningRecord entities.
func (c *SigningRecordClient) CreateBulk(builders ...*SigningRecordCreate) *SigningRecordCreateBulk {
	return &SigningRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SigningRecordClient) MapCreateBulk(slice any, setFunc func(*SigningRecordCreate, int)) *SigningRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SigningRecordCreateBulk{err: fmt.Errorf("calling to SigningRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SigningRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SigningRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SigningRecord.
func (c *SigningRecordClient) Update() *SigningRecordUpdate {
	mutation := newSigningRecordMutation(c.config, OpUpdate)
	return &SigningRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SigningRecordClient) UpdateOne(_m *SigningRecord) *SigningRecordUpdateOne {
	mutation := newSigningRecordMutation(c.config, OpUpdateOne, withSigningRecord(_m))
	return &SigningRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SigningRecordClient) UpdateOneID(id string) *SigningRecordUpdateOne {
	mutation := newSigningRecordMutation(c.config, OpUpdateOne, withSigningRecordID(id))
	return &SigningRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SigningRecord.
func (c *SigningRecordClient) Delete() *SigningRecordDelete {
	mutation := newSigningRecordMutation(c.config, OpDelete)
	return &SigningRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SigningRecordClient) DeleteOne(_m *SigningRecord) *SigningRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SigningRecordClient) DeleteOneID(id string) *SigningRecordDeleteOne {
	builder := c.Delete().Where(signingrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SigningRecordDeleteOne{builder}
}

// Query returns a query builder for SigningRecord.
func (c *SigningRecordClient) Query() *SigningRecordQuery {
	return &SigningRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSigningRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a SigningRecord entity by its id.
func (c *SigningRecordClient) Get(ctx context.Context, id string) (*SigningRecord, error) {
	return c.Query().Where(signingrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SigningRecordClient) GetX(ctx context.Context, id string) *SigningRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SigningRecordClient) Hooks() []Hook {
	return c.hooks.SigningRecord
}

// Interceptors returns the client interceptors.
func (c *SigningRecordClient) Interceptors() []Interceptor {
	return c.inters.SigningRecord
}

func (c *SigningRecordClient) mutate(ctx context.Context, m *SigningRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SigningRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SigningRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SigningRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SigningRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SigningRecord mutation op: %q", m.Op())
	}
}

// UnsealKeySlotClient is a client for the UnsealKeySlot schema.
type UnsealKeySlotClient struct {
	config
}

// NewUnsealKeySlotClient returns a client for the UnsealKeySlot from the given config.
func NewUnsealKeySlotClient(c config) *UnsealKeySlotClient {
	return &UnsealKeySlotClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `unsealkeyslot.Hooks(f(g(h())))`.
func (c *UnsealKeySlotClient) Use(hooks ...Hook) {
	c.hooks.UnsealKeySlot = append(c.hooks.UnsealKeySlot, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `unsealkeyslot.Intercept(f(g(h())))`.
func (c *UnsealKeySlotClient) Intercept(interceptors ...Interceptor) {
	c.inters.UnsealKeySlot = append(c.inters.UnsealKeySlot, interceptors...)
}

// Create returns a builder for creating a UnsealKeySlot entity.
func (c *UnsealKeySlotClient) Create() *UnsealKeySlotCreate {
	mutation := newUnsealKeySlotMutation(c.config, OpCreate)
	return &UnsealKeySlotCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UnsealKeySlot entities.
func (c *UnsealKeySlotClient) CreateBulk(builders ...*UnsealKeySlotCreate) *UnsealKeySlotCreateBulk {
	return &UnsealKeySlotCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UnsealKeySlotClient) MapCreateBulk(slice any, setFunc func(*UnsealKeySlotCreate, int)) *UnsealKeySlotCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UnsealKeySlotCreateBulk{err: fmt.Errorf("calling to UnsealKeySlotClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UnsealKeySlotCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UnsealKeySlotCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UnsealKeySlot.
func (c *UnsealKeySlotClient) Update() *UnsealKeySlotUpdate {
	mutation := newUnsealKeySlotMutation(c.config, OpUpdate)
	return &UnsealKeySlotUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UnsealKeySlotClient) UpdateOne(_m *UnsealKeySlot) *UnsealKeySlotUpdateOne {
	mutation := newUnsealKeySlotMutation(c.config, OpUpdateOne, withUnsealKeySlot(_m))
	return &UnsealKeySlotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UnsealKeySlotClient) UpdateOneID(id int) *UnsealKeySlotUpdateOne {
	mutation := newUnsealKeySlotMutation(c.config, OpUpdateOne, withUnsealKeySlotID(id))
	return &UnsealKeySlotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UnsealKeySlot.
func (c *UnsealKeySlotClient) Delete() *UnsealKeySlotDelete {
	mutation := newUnsealKeySlotMutation(c.config, OpDelete)
	return &UnsealKeySlotDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UnsealKeySlotClient) DeleteOne(_m *UnsealKeySlot) *UnsealKeySlotDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UnsealKeySlotClient) DeleteOneID(id int) *UnsealKeySlotDeleteOne {
	builder := c.Delete().Where(unsealkeyslot.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UnsealKeySlotDeleteOne{builder}
}

// Query returns a query builder for UnsealKeySlot.
func (c *UnsealKeySlotClient) Query() *UnsealKeySlotQuery {
	return &UnsealKeySlotQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUnsealKeySlot},
		inters: c.Interceptors(),
	}
}

// Get returns a UnsealKeySlot entity by its id.
func (c *UnsealKeySlotClient) Get(ctx context.Context, id int) (*UnsealKeySlot, error) {
	return c.Query().Where(unsealkeyslot.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UnsealKeySlotClient) GetX(ctx context.Context, id int) *UnsealKeySlot {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UnsealKeySlotClient) Hooks() []Hook {
	return c.hooks.UnsealKeySlot
}

// Interceptors returns the client interceptors.
func (c *UnsealKeySlotClient) Interceptors() []Interceptor {
	return c.inters.UnsealKeySlot
}

func (c *UnsealKeySlotClient) mutate(ctx context.Context, m *UnsealKeySlotMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UnsealKeySlotCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UnsealKeySlotUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UnsealKeySlotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UnsealKeySlotDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UnsealKeySlot mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id string) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id string) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id string) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id string) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRole queries the role edge of a User.
func (c *UserClient) QueryRole(_m *User) *RoleQuery {
	query := (&RoleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.RoleTable, user.RoleColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySessions queries the sessions edge of a User.
func (c *UserClient) QuerySessions(_m *User) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.SessionsTable, user.SessionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// WalletClient is a client for the Wallet schema.
type WalletClient struct {
	config
}

// NewWalletClient returns a client for the Wallet from the given config.
func NewWalletClient(c config) *WalletClient {
	return &WalletClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `wallet.Hooks(f(g(h())))`.
func (c *WalletClient) Use(hooks ...Hook) {
	c.hooks.Wallet = append(c.hooks.Wallet, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `wallet.Intercept(f(g(h())))`.
func (c *WalletClient) Intercept(interceptors ...Interceptor) {
	c.inters.Wallet = append(c.inters.Wallet, interceptors...)
}

// Create returns a builder for creating a Wallet entity.
func (c *WalletClient) Create() *WalletCreate {
	mutation := newWalletMutation(c.config, OpCreate)
	return &WalletCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Wallet entities.
func (c *WalletClient) CreateBulk(builders ...*WalletCreate) *WalletCreateBulk {
	return &WalletCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WalletClient) MapCreateBulk(slice any, setFunc func(*WalletCreate, int)) *WalletCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WalletCreateBulk{err: fmt.Errorf("calling to WalletClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WalletCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WalletCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Wallet.
func (c *WalletClient) Update() *WalletUpdate {
	mutation := newWalletMutation(c.config, OpUpdate)
	return &WalletUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WalletClient) UpdateOne(_m *Wallet) *WalletUpdateOne {
	mutation := newWalletMutation(c.config, OpUpdateOne, withWallet(_m))
	return &WalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WalletClient) UpdateOneID(id string) *WalletUpdateOne {
	mutation := newWalletMutation(c.config, OpUpdateOne, withWalletID(id))
	return &WalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Wallet.
func (c *WalletClient) Delete() *WalletDelete {
	mutation := newWalletMutation(c.config, OpDelete)
	return &WalletDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WalletClient) DeleteOne(_m *Wallet) *WalletDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WalletClient) DeleteOneID(id string) *WalletDeleteOne {
	builder := c.Delete().Where(wallet.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WalletDeleteOne{builder}
}

// Query returns a query builder for Wallet.
func (c *WalletClient) Query() *WalletQuery {
	return &WalletQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWallet},
		inters: c.Interceptors(),
	}
}

// Get returns a Wallet entity by its id.
func (c *WalletClient) Get(ctx context.Context, id string) (*Wallet, error) {
	return c.Query().Where(wallet.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WalletClient) GetX(ctx context.Context, id string) *Wallet {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryKeyRoot queries the key_root edge of a Wallet.
func (c *WalletClient) QueryKeyRoot(_m *Wallet) *KeyRootQuery {
	query := (&KeyRootClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(wallet.Table, wallet.FieldID, id),
			sqlgraph.To(keyroot.Table, keyroot.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wallet.KeyRootTable, wallet.KeyRootColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WalletClient) Hooks() []Hook {
	return c.hooks.Wallet
}

// Interceptors returns the client interceptors.
func (c *WalletClient) Interceptors() []Interceptor {
	return c.inters.Wallet
}

func (c *WalletClient) mutate(ctx context.Context, m *WalletMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WalletCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WalletUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WalletDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Wallet mutation op: %q", m.Op())
	}
}

// WalletCounterClient is a client for the WalletCounter schema.
type WalletCounterClient struct {
	config
}

// NewWalletCounterClient returns a client for the WalletCounter from the given config.
func NewWalletCounterClient(c config) *WalletCounterClient {
	return &WalletCounterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `walletcounter.Hooks(f(g(h())))`.
func (c *WalletCounterClient) Use(hooks ...Hook) {
	c.hooks.WalletCounter = append(c.hooks.WalletCounter, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `walletcounter.Intercept(f(g(h())))`.
func (c *WalletCounterClient) Intercept(interceptors ...Interceptor) {
	c.inters.WalletCounter = append(c.inters.WalletCounter, interceptors...)
}

// Create returns a builder for creating a WalletCounter entity.
func (c *WalletCounterClient) Create() *WalletCounterCreate {
	mutation := newWalletCounterMutation(c.config, OpCreate)
	return &WalletCounterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WalletCounter entities.
func (c *WalletCounterClient) CreateBulk(builders ...*WalletCounterCreate) *WalletCounterCreateBulk {
	return &WalletCounterCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WalletCounterClient) MapCreateBulk(slice any, setFunc func(*WalletCounterCreate, int)) *WalletCounterCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WalletCounterCreateBulk{err: fmt.Errorf("calling to WalletCounterClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WalletCounterCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WalletCounterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WalletCounter.
func (c *WalletCounterClient) Update() *WalletCounterUpdate {
	mutation := newWalletCounterMutation(c.config, OpUpdate)
	return &WalletCounterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WalletCounterClient) UpdateOne(_m *WalletCounter) *WalletCounterUpdateOne {
	mutation := newWalletCounterMutation(c.config, OpUpdateOne, withWalletCounter(_m))
	return &WalletCounterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WalletCounterClient) UpdateOneID(id int) *WalletCounterUpdateOne {
	mutation := newWalletCounterMutation(c.config, OpUpdateOne, withWalletCounterID(id))
	return &WalletCounterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WalletCounter.
func (c *WalletCounterClient) Delete() *WalletCounterDelete {
	mutation := newWalletCounterMutation(c.config, OpDelete)
	return &WalletCounterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WalletCounterClient) DeleteOne(_m *WalletCounter) *WalletCounterDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WalletCounterClient) DeleteOneID(id int) *WalletCounterDeleteOne {
	builder := c.Delete().Where(walletcounter.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WalletCounterDeleteOne{builder}
}

// Query returns a query builder for WalletCounter.
func (c *WalletCounterClient) Query() *WalletCounterQuery {
	return &WalletCounterQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWalletCounter},
		inters: c.Interceptors(),
	}
}

// Get returns a WalletCounter entity by its id.
func (c *WalletCounterClient) Get(ctx context.Context, id int) (*WalletCounter, error) {
	return c.Query().Where(walletcounter.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WalletCounterClient) GetX(ctx context.Context, id int) *WalletCounter {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryKeyRoot queries the key_root edge of a WalletCounter.
func (c *WalletCounterClient) QueryKeyRoot(_m *WalletCounter) *KeyRootQuery {
	query := (&KeyRootClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(walletcounter.Table, walletcounter.FieldID, id),
			sqlgraph.To(keyroot.Table, keyroot.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, walletcounter.KeyRootTable, walletcounter.KeyRootColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WalletCounterClient) Hooks() []Hook {
	return c.hooks.WalletCounter
}

// Interceptors returns the client interceptors.
func (c *WalletCounterClient) Interceptors() []Interceptor {
	return c.inters.WalletCounter
}

func (c *WalletCounterClient) mutate(ctx context.Context, m *WalletCounterMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WalletCounterCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WalletCounterUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WalletCounterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WalletCounterDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WalletCounter mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AuditEvent, KeyRoot, Role, ServiceAccount, Session, SigningRecord,
		UnsealKeySlot, User, Wallet, WalletCounter []ent.Hook
	}
	inters struct {
		AuditEvent, KeyRoot, Role, ServiceAccount, Session, SigningRecord,
		UnsealKeySlot, User, Wallet, WalletCounter []ent.Interceptor
	}
)
