// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/rajabinekoo/sigryx/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rajabinekoo/sigryx/internal/ent/keyroot"
	"github.com/rajabinekoo/sigryx/internal/ent/unsealkeyslot"
	"github.com/rajabinekoo/sigryx/internal/ent/wallet"
	"github.com/rajabinekoo/sigryx/internal/ent/walletcounter"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// KeyRoot is the client for interacting with the KeyRoot builders.
	KeyRoot *KeyRootClient
	// UnsealKeySlot is the client for interacting with the UnsealKeySlot builders.
	UnsealKeySlot *UnsealKeySlotClient
	// Wallet is the client for interacting with the Wallet builders.
	Wallet *WalletClient
	// WalletCounter is the client for interacting with the WalletCounter builders.
	WalletCounter *WalletCounterClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.KeyRoot = NewKeyRootClient(c.config)
	c.UnsealKeySlot = NewUnsealKeySlotClient(c.config)
	c.Wallet = NewWalletClient(c.config)
	c.WalletCounter = NewWalletCounterClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		KeyRoot:       NewKeyRootClient(cfg),
		UnsealKeySlot: NewUnsealKeySlotClient(cfg),
		Wallet:        NewWalletClient(cfg),
		WalletCounter: NewWalletCounterClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		KeyRoot:       NewKeyRootClient(cfg),
		UnsealKeySlot: NewUnsealKeySlotClient(cfg),
		Wallet:        NewWalletClient(cfg),
		WalletCounter: NewWalletCounterClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		KeyRoot.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.KeyRoot.Use(hooks...)
	c.UnsealKeySlot.Use(hooks...)
	c.Wallet.Use(hooks...)
	c.WalletCounter.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.KeyRoot.Intercept(interceptors...)
	c.UnsealKeySlot.Intercept(interceptors...)
	c.Wallet.Intercept(interceptors...)
	c.WalletCounter.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *KeyRootMutation:
		return c.KeyRoot.mutate(ctx, m)
	case *UnsealKeySlotMutation:
		return c.UnsealKeySlot.mutate(ctx, m)
	case *WalletMutation:
		return c.Wallet.mutate(ctx, m)
	case *WalletCounterMutation:
		return c.WalletCounter.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// KeyRootClient is a client for the KeyRoot schema.
type KeyRootClient struct {
	config
}

// NewKeyRootClient returns a client for the KeyRoot from the given config.
func NewKeyRootClient(c config) *KeyRootClient {
	return &KeyRootClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `keyroot.Hooks(f(g(h())))`.
func (c *KeyRootClient) Use(hooks ...Hook) {
	c.hooks.KeyRoot = append(c.hooks.KeyRoot, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `keyroot.Intercept(f(g(h())))`.
func (c *KeyRootClient) Intercept(interceptors ...Interceptor) {
	c.inters.KeyRoot = append(c.inters.KeyRoot, interceptors...)
}

// Create returns a builder for creating a KeyRoot entity.
func (c *KeyRootClient) Create() *KeyRootCreate {
	mutation := newKeyRootMutation(c.config, OpCreate)
	return &KeyRootCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of KeyRoot entities.
func (c *KeyRootClient) CreateBulk(builders ...*KeyRootCreate) *KeyRootCreateBulk {
	return &KeyRootCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *KeyRootClient) MapCreateBulk(slice any, setFunc func(*KeyRootCreate, int)) *KeyRootCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &KeyRootCreateBulk{err: fmt.Errorf("calling to KeyRootClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*KeyRootCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &KeyRootCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for KeyRoot.
func (c *KeyRootClient) Update() *KeyRootUpdate {
	mutation := newKeyRootMutation(c.config, OpUpdate)
	return &KeyRootUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *KeyRootClient) UpdateOne(_m *KeyRoot) *KeyRootUpdateOne {
	mutation := newKeyRootMutation(c.config, OpUpdateOne, withKeyRoot(_m))
	return &KeyRootUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *KeyRootClient) UpdateOneID(id string) *KeyRootUpdateOne {
	mutation := newKeyRootMutation(c.config, OpUpdateOne, withKeyRootID(id))
	return &KeyRootUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for KeyRoot.
func (c *KeyRootClient) Delete() *KeyRootDelete {
	mutation := newKeyRootMutation(c.config, OpDelete)
	return &KeyRootDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *KeyRootClient) DeleteOne(_m *KeyRoot) *KeyRootDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *KeyRootClient) DeleteOneID(id string) *KeyRootDeleteOne {
	builder := c.Delete().Where(keyroot.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &KeyRootDeleteOne{builder}
}

// Query returns a query builder for KeyRoot.
func (c *KeyRootClient) Query() *KeyRootQuery {
	return &KeyRootQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeKeyRoot},
		inters: c.Interceptors(),
	}
}

// Get returns a KeyRoot entity by its id.
func (c *KeyRootClient) Get(ctx context.Context, id string) (*KeyRoot, error) {
	return c.Query().Where(keyroot.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *KeyRootClient) GetX(ctx context.Context, id string) *KeyRoot {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryWallets queries the wallets edge of a KeyRoot.
func (c *KeyRootClient) QueryWallets(_m *KeyRoot) *WalletQuery {
	query := (&WalletClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(keyroot.Table, keyroot.FieldID, id),
			sqlgraph.To(wallet.Table, wallet.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, keyroot.WalletsTable, keyroot.WalletsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryWalletCounters queries the wallet_counters edge of a KeyRoot.
func (c *KeyRootClient) QueryWalletCounters(_m *KeyRoot) *WalletCounterQuery {
	query := (&WalletCounterClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(keyroot.Table, keyroot.FieldID, id),
			sqlgraph.To(walletcounter.Table, walletcounter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, keyroot.WalletCountersTable, keyroot.WalletCountersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *KeyRootClient) Hooks() []Hook {
	return c.hooks.KeyRoot
}

// Interceptors returns the client interceptors.
func (c *KeyRootClient) Interceptors() []Interceptor {
	return c.inters.KeyRoot
}

func (c *KeyRootClient) mutate(ctx context.Context, m *KeyRootMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&KeyRootCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&KeyRootUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&KeyRootUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&KeyRootDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown KeyRoot mutation op: %q", m.Op())
	}
}

// UnsealKeySlotClient is a client for the UnsealKeySlot schema.
type UnsealKeySlotClient struct {
	config
}

// NewUnsealKeySlotClient returns a client for the UnsealKeySlot from the given config.
func NewUnsealKeySlotClient(c config) *UnsealKeySlotClient {
	return &UnsealKeySlotClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `unsealkeyslot.Hooks(f(g(h())))`.
func (c *UnsealKeySlotClient) Use(hooks ...Hook) {
	c.hooks.UnsealKeySlot = append(c.hooks.UnsealKeySlot, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `unsealkeyslot.Intercept(f(g(h())))`.
func (c *UnsealKeySlotClient) Intercept(interceptors ...Interceptor) {
	c.inters.UnsealKeySlot = append(c.inters.UnsealKeySlot, interceptors...)
}

// Create returns a builder for creating a UnsealKeySlot entity.
func (c *UnsealKeySlotClient) Create() *UnsealKeySlotCreate {
	mutation := newUnsealKeySlotMutation(c.config, OpCreate)
	return &UnsealKeySlotCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UnsealKeySlot entities.
func (c *UnsealKeySlotClient) CreateBulk(builders ...*UnsealKeySlotCreate) *UnsealKeySlotCreateBulk {
	return &UnsealKeySlotCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UnsealKeySlotClient) MapCreateBulk(slice any, setFunc func(*UnsealKeySlotCreate, int)) *UnsealKeySlotCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UnsealKeySlotCreateBulk{err: fmt.Errorf("calling to UnsealKeySlotClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UnsealKeySlotCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UnsealKeySlotCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UnsealKeySlot.
func (c *UnsealKeySlotClient) Update() *UnsealKeySlotUpdate {
	mutation := newUnsealKeySlotMutation(c.config, OpUpdate)
	return &UnsealKeySlotUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UnsealKeySlotClient) UpdateOne(_m *UnsealKeySlot) *UnsealKeySlotUpdateOne {
	mutation := newUnsealKeySlotMutation(c.config, OpUpdateOne, withUnsealKeySlot(_m))
	return &UnsealKeySlotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UnsealKeySlotClient) UpdateOneID(id int) *UnsealKeySlotUpdateOne {
	mutation := newUnsealKeySlotMutation(c.config, OpUpdateOne, withUnsealKeySlotID(id))
	return &UnsealKeySlotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UnsealKeySlot.
func (c *UnsealKeySlotClient) Delete() *UnsealKeySlotDelete {
	mutation := newUnsealKeySlotMutation(c.config, OpDelete)
	return &UnsealKeySlotDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UnsealKeySlotClient) DeleteOne(_m *UnsealKeySlot) *UnsealKeySlotDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UnsealKeySlotClient) DeleteOneID(id int) *UnsealKeySlotDeleteOne {
	builder := c.Delete().Where(unsealkeyslot.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UnsealKeySlotDeleteOne{builder}
}

// Query returns a query builder for UnsealKeySlot.
func (c *UnsealKeySlotClient) Query() *UnsealKeySlotQuery {
	return &UnsealKeySlotQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUnsealKeySlot},
		inters: c.Interceptors(),
	}
}

// Get returns a UnsealKeySlot entity by its id.
func (c *UnsealKeySlotClient) Get(ctx context.Context, id int) (*UnsealKeySlot, error) {
	return c.Query().Where(unsealkeyslot.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UnsealKeySlotClient) GetX(ctx context.Context, id int) *UnsealKeySlot {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UnsealKeySlotClient) Hooks() []Hook {
	return c.hooks.UnsealKeySlot
}

// Interceptors returns the client interceptors.
func (c *UnsealKeySlotClient) Interceptors() []Interceptor {
	return c.inters.UnsealKeySlot
}

func (c *UnsealKeySlotClient) mutate(ctx context.Context, m *UnsealKeySlotMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UnsealKeySlotCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UnsealKeySlotUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UnsealKeySlotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UnsealKeySlotDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UnsealKeySlot mutation op: %q", m.Op())
	}
}

// WalletClient is a client for the Wallet schema.
type WalletClient struct {
	config
}

// NewWalletClient returns a client for the Wallet from the given config.
func NewWalletClient(c config) *WalletClient {
	return &WalletClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `wallet.Hooks(f(g(h())))`.
func (c *WalletClient) Use(hooks ...Hook) {
	c.hooks.Wallet = append(c.hooks.Wallet, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `wallet.Intercept(f(g(h())))`.
func (c *WalletClient) Intercept(interceptors ...Interceptor) {
	c.inters.Wallet = append(c.inters.Wallet, interceptors...)
}

// Create returns a builder for creating a Wallet entity.
func (c *WalletClient) Create() *WalletCreate {
	mutation := newWalletMutation(c.config, OpCreate)
	return &WalletCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Wallet entities.
func (c *WalletClient) CreateBulk(builders ...*WalletCreate) *WalletCreateBulk {
	return &WalletCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WalletClient) MapCreateBulk(slice any, setFunc func(*WalletCreate, int)) *WalletCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WalletCreateBulk{err: fmt.Errorf("calling to WalletClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WalletCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WalletCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Wallet.
func (c *WalletClient) Update() *WalletUpdate {
	mutation := newWalletMutation(c.config, OpUpdate)
	return &WalletUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WalletClient) UpdateOne(_m *Wallet) *WalletUpdateOne {
	mutation := newWalletMutation(c.config, OpUpdateOne, withWallet(_m))
	return &WalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WalletClient) UpdateOneID(id string) *WalletUpdateOne {
	mutation := newWalletMutation(c.config, OpUpdateOne, withWalletID(id))
	return &WalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Wallet.
func (c *WalletClient) Delete() *WalletDelete {
	mutation := newWalletMutation(c.config, OpDelete)
	return &WalletDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WalletClient) DeleteOne(_m *Wallet) *WalletDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WalletClient) DeleteOneID(id string) *WalletDeleteOne {
	builder := c.Delete().Where(wallet.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WalletDeleteOne{builder}
}

// Query returns a query builder for Wallet.
func (c *WalletClient) Query() *WalletQuery {
	return &WalletQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWallet},
		inters: c.Interceptors(),
	}
}

// Get returns a Wallet entity by its id.
func (c *WalletClient) Get(ctx context.Context, id string) (*Wallet, error) {
	return c.Query().Where(wallet.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WalletClient) GetX(ctx context.Context, id string) *Wallet {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryKeyRoot queries the key_root edge of a Wallet.
func (c *WalletClient) QueryKeyRoot(_m *Wallet) *KeyRootQuery {
	query := (&KeyRootClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(wallet.Table, wallet.FieldID, id),
			sqlgraph.To(keyroot.Table, keyroot.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wallet.KeyRootTable, wallet.KeyRootColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WalletClient) Hooks() []Hook {
	return c.hooks.Wallet
}

// Interceptors returns the client interceptors.
func (c *WalletClient) Interceptors() []Interceptor {
	return c.inters.Wallet
}

func (c *WalletClient) mutate(ctx context.Context, m *WalletMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WalletCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WalletUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WalletDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Wallet mutation op: %q", m.Op())
	}
}

// WalletCounterClient is a client for the WalletCounter schema.
type WalletCounterClient struct {
	config
}

// NewWalletCounterClient returns a client for the WalletCounter from the given config.
func NewWalletCounterClient(c config) *WalletCounterClient {
	return &WalletCounterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `walletcounter.Hooks(f(g(h())))`.
func (c *WalletCounterClient) Use(hooks ...Hook) {
	c.hooks.WalletCounter = append(c.hooks.WalletCounter, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `walletcounter.Intercept(f(g(h())))`.
func (c *WalletCounterClient) Intercept(interceptors ...Interceptor) {
	c.inters.WalletCounter = append(c.inters.WalletCounter, interceptors...)
}

// Create returns a builder for creating a WalletCounter entity.
func (c *WalletCounterClient) Create() *WalletCounterCreate {
	mutation := newWalletCounterMutation(c.config, OpCreate)
	return &WalletCounterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WalletCounter entities.
func (c *WalletCounterClient) CreateBulk(builders ...*WalletCounterCreate) *WalletCounterCreateBulk {
	return &WalletCounterCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WalletCounterClient) MapCreateBulk(slice any, setFunc func(*WalletCounterCreate, int)) *WalletCounterCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WalletCounterCreateBulk{err: fmt.Errorf("calling to WalletCounterClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WalletCounterCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WalletCounterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WalletCounter.
func (c *WalletCounterClient) Update() *WalletCounterUpdate {
	mutation := newWalletCounterMutation(c.config, OpUpdate)
	return &WalletCounterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WalletCounterClient) UpdateOne(_m *WalletCounter) *WalletCounterUpdateOne {
	mutation := newWalletCounterMutation(c.config, OpUpdateOne, withWalletCounter(_m))
	return &WalletCounterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WalletCounterClient) UpdateOneID(id int) *WalletCounterUpdateOne {
	mutation := newWalletCounterMutation(c.config, OpUpdateOne, withWalletCounterID(id))
	return &WalletCounterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WalletCounter.
func (c *WalletCounterClient) Delete() *WalletCounterDelete {
	mutation := newWalletCounterMutation(c.config, OpDelete)
	return &WalletCounterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WalletCounterClient) DeleteOne(_m *WalletCounter) *WalletCounterDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WalletCounterClient) DeleteOneID(id int) *WalletCounterDeleteOne {
	builder := c.Delete().Where(walletcounter.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WalletCounterDeleteOne{builder}
}

// Query returns a query builder for WalletCounter.
func (c *WalletCounterClient) Query() *WalletCounterQuery {
	return &WalletCounterQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWalletCounter},
		inters: c.Interceptors(),
	}
}

// Get returns a WalletCounter entity by its id.
func (c *WalletCounterClient) Get(ctx context.Context, id int) (*WalletCounter, error) {
	return c.Query().Where(walletcounter.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WalletCounterClient) GetX(ctx context.Context, id int) *WalletCounter {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryKeyRoot queries the key_root edge of a WalletCounter.
func (c *WalletCounterClient) QueryKeyRoot(_m *WalletCounter) *KeyRootQuery {
	query := (&KeyRootClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(walletcounter.Table, walletcounter.FieldID, id),
			sqlgraph.To(keyroot.Table, keyroot.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, walletcounter.KeyRootTable, walletcounter.KeyRootColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WalletCounterClient) Hooks() []Hook {
	return c.hooks.WalletCounter
}

// Interceptors returns the client interceptors.
func (c *WalletCounterClient) Interceptors() []Interceptor {
	return c.inters.WalletCounter
}

func (c *WalletCounterClient) mutate(ctx context.Context, m *WalletCounterMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WalletCounterCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WalletCounterUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WalletCounterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WalletCounterDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WalletCounter mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		KeyRoot, UnsealKeySlot, Wallet, WalletCounter []ent.Hook
	}
	inters struct {
		KeyRoot, UnsealKeySlot, Wallet, WalletCounter []ent.Interceptor
	}
)
