// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rajabinekoo/sigryx/internal/ent/keyroot"
)

// KeyRoot is the model entity for the KeyRoot schema.
type KeyRoot struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// DerivationScheme holds the value of the "derivation_scheme" field.
	DerivationScheme string `json:"derivation_scheme,omitempty"`
	// SealedSeed holds the value of the "sealed_seed" field.
	SealedSeed []byte `json:"sealed_seed,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the KeyRootQuery when eager-loading is set.
	Edges        KeyRootEdges `json:"edges"`
	selectValues sql.SelectValues
}

// KeyRootEdges holds the relations/edges for other nodes in the graph.
type KeyRootEdges struct {
	// Wallets holds the value of the wallets edge.
	Wallets []*Wallet `json:"wallets,omitempty"`
	// WalletCounters holds the value of the wallet_counters edge.
	WalletCounters []*WalletCounter `json:"wallet_counters,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// WalletsOrErr returns the Wallets value or an error if the edge
// was not loaded in eager-loading.
func (e KeyRootEdges) WalletsOrErr() ([]*Wallet, error) {
	if e.loadedTypes[0] {
		return e.Wallets, nil
	}
	return nil, &NotLoadedError{edge: "wallets"}
}

// WalletCountersOrErr returns the WalletCounters value or an error if the edge
// was not loaded in eager-loading.
func (e KeyRootEdges) WalletCountersOrErr() ([]*WalletCounter, error) {
	if e.loadedTypes[1] {
		return e.WalletCounters, nil
	}
	return nil, &NotLoadedError{edge: "wallet_counters"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KeyRoot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case keyroot.FieldSealedSeed:
			values[i] = new([]byte)
		case keyroot.FieldID, keyroot.FieldDerivationScheme:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KeyRoot fields.
func (_m *KeyRoot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case keyroot.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case keyroot.FieldDerivationScheme:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field derivation_scheme", values[i])
			} else if value.Valid {
				_m.DerivationScheme = value.String
			}
		case keyroot.FieldSealedSeed:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field sealed_seed", values[i])
			} else if value != nil {
				_m.SealedSeed = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KeyRoot.
// This includes values selected through modifiers, order, etc.
func (_m *KeyRoot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWallets queries the "wallets" edge of the KeyRoot entity.
func (_m *KeyRoot) QueryWallets() *WalletQuery {
	return NewKeyRootClient(_m.config).QueryWallets(_m)
}

// QueryWalletCounters queries the "wallet_counters" edge of the KeyRoot entity.
func (_m *KeyRoot) QueryWalletCounters() *WalletCounterQuery {
	return NewKeyRootClient(_m.config).QueryWalletCounters(_m)
}

// Update returns a builder for updating this KeyRoot.
// Note that you need to call KeyRoot.Unwrap() before calling this method if this KeyRoot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KeyRoot) Update() *KeyRootUpdateOne {
	return NewKeyRootClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KeyRoot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KeyRoot) Unwrap() *KeyRoot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KeyRoot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KeyRoot) String() string {
	var builder strings.Builder
	builder.WriteString("KeyRoot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("derivation_scheme=")
	builder.WriteString(_m.DerivationScheme)
	builder.WriteString(", ")
	builder.WriteString("sealed_seed=")
	builder.WriteString(fmt.Sprintf("%v", _m.SealedSeed))
	builder.WriteByte(')')
	return builder.String()
}

// KeyRoots is a parsable slice of KeyRoot.
type KeyRoots []*KeyRoot
