// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rajabinekoo/sigryx/internal/ent/keyroot"
	"github.com/rajabinekoo/sigryx/internal/ent/predicate"
	"github.com/rajabinekoo/sigryx/internal/ent/wallet"
	"github.com/rajabinekoo/sigryx/internal/ent/walletcounter"
)

// KeyRootUpdate is the builder for updating KeyRoot entities.
type KeyRootUpdate struct {
	config
	hooks    []Hook
	mutation *KeyRootMutation
}

// Where appends a list predicates to the KeyRootUpdate builder.
func (_u *KeyRootUpdate) Where(ps ...predicate.KeyRoot) *KeyRootUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// AddWalletIDs adds the "wallets" edge to the Wallet entity by IDs.
func (_u *KeyRootUpdate) AddWalletIDs(ids ...string) *KeyRootUpdate {
	_u.mutation.AddWalletIDs(ids...)
	return _u
}

// AddWallets adds the "wallets" edges to the Wallet entity.
func (_u *KeyRootUpdate) AddWallets(v ...*Wallet) *KeyRootUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWalletIDs(ids...)
}

// AddWalletCounterIDs adds the "wallet_counters" edge to the WalletCounter entity by IDs.
func (_u *KeyRootUpdate) AddWalletCounterIDs(ids ...int) *KeyRootUpdate {
	_u.mutation.AddWalletCounterIDs(ids...)
	return _u
}

// AddWalletCounters adds the "wallet_counters" edges to the WalletCounter entity.
func (_u *KeyRootUpdate) AddWalletCounters(v ...*WalletCounter) *KeyRootUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWalletCounterIDs(ids...)
}

// Mutation returns the KeyRootMutation object of the builder.
func (_u *KeyRootUpdate) Mutation() *KeyRootMutation {
	return _u.mutation
}

// ClearWallets clears all "wallets" edges to the Wallet entity.
func (_u *KeyRootUpdate) ClearWallets() *KeyRootUpdate {
	_u.mutation.ClearWallets()
	return _u
}

// RemoveWalletIDs removes the "wallets" edge to Wallet entities by IDs.
func (_u *KeyRootUpdate) RemoveWalletIDs(ids ...string) *KeyRootUpdate {
	_u.mutation.RemoveWalletIDs(ids...)
	return _u
}

// RemoveWallets removes "wallets" edges to Wallet entities.
func (_u *KeyRootUpdate) RemoveWallets(v ...*Wallet) *KeyRootUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWalletIDs(ids...)
}

// ClearWalletCounters clears all "wallet_counters" edges to the WalletCounter entity.
func (_u *KeyRootUpdate) ClearWalletCounters() *KeyRootUpdate {
	_u.mutation.ClearWalletCounters()
	return _u
}

// RemoveWalletCounterIDs removes the "wallet_counters" edge to WalletCounter entities by IDs.
func (_u *KeyRootUpdate) RemoveWalletCounterIDs(ids ...int) *KeyRootUpdate {
	_u.mutation.RemoveWalletCounterIDs(ids...)
	return _u
}

// RemoveWalletCounters removes "wallet_counters" edges to WalletCounter entities.
func (_u *KeyRootUpdate) RemoveWalletCounters(v ...*WalletCounter) *KeyRootUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWalletCounterIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KeyRootUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeyRootUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KeyRootUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeyRootUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *KeyRootUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(keyroot.Table, keyroot.Columns, sqlgraph.NewFieldSpec(keyroot.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.WalletsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletsTable,
			Columns: []string{keyroot.WalletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWalletsIDs(); len(nodes) > 0 && !_u.mutation.WalletsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletsTable,
			Columns: []string{keyroot.WalletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletsTable,
			Columns: []string{keyroot.WalletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WalletCountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletCountersTable,
			Columns: []string{keyroot.WalletCountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(walletcounter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWalletCountersIDs(); len(nodes) > 0 && !_u.mutation.WalletCountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletCountersTable,
			Columns: []string{keyroot.WalletCountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(walletcounter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletCountersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletCountersTable,
			Columns: []string{keyroot.WalletCountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(walletcounter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keyroot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KeyRootUpdateOne is the builder for updating a single KeyRoot entity.
type KeyRootUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KeyRootMutation
}

// AddWalletIDs adds the "wallets" edge to the Wallet entity by IDs.
func (_u *KeyRootUpdateOne) AddWalletIDs(ids ...string) *KeyRootUpdateOne {
	_u.mutation.AddWalletIDs(ids...)
	return _u
}

// AddWallets adds the "wallets" edges to the Wallet entity.
func (_u *KeyRootUpdateOne) AddWallets(v ...*Wallet) *KeyRootUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWalletIDs(ids...)
}

// AddWalletCounterIDs adds the "wallet_counters" edge to the WalletCounter entity by IDs.
func (_u *KeyRootUpdateOne) AddWalletCounterIDs(ids ...int) *KeyRootUpdateOne {
	_u.mutation.AddWalletCounterIDs(ids...)
	return _u
}

// AddWalletCounters adds the "wallet_counters" edges to the WalletCounter entity.
func (_u *KeyRootUpdateOne) AddWalletCounters(v ...*WalletCounter) *KeyRootUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWalletCounterIDs(ids...)
}

// Mutation returns the KeyRootMutation object of the builder.
func (_u *KeyRootUpdateOne) Mutation() *KeyRootMutation {
	return _u.mutation
}

// ClearWallets clears all "wallets" edges to the Wallet entity.
func (_u *KeyRootUpdateOne) ClearWallets() *KeyRootUpdateOne {
	_u.mutation.ClearWallets()
	return _u
}

// RemoveWalletIDs removes the "wallets" edge to Wallet entities by IDs.
func (_u *KeyRootUpdateOne) RemoveWalletIDs(ids ...string) *KeyRootUpdateOne {
	_u.mutation.RemoveWalletIDs(ids...)
	return _u
}

// RemoveWallets removes "wallets" edges to Wallet entities.
func (_u *KeyRootUpdateOne) RemoveWallets(v ...*Wallet) *KeyRootUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWalletIDs(ids...)
}

// ClearWalletCounters clears all "wallet_counters" edges to the WalletCounter entity.
func (_u *KeyRootUpdateOne) ClearWalletCounters() *KeyRootUpdateOne {
	_u.mutation.ClearWalletCounters()
	return _u
}

// RemoveWalletCounterIDs removes the "wallet_counters" edge to WalletCounter entities by IDs.
func (_u *KeyRootUpdateOne) RemoveWalletCounterIDs(ids ...int) *KeyRootUpdateOne {
	_u.mutation.RemoveWalletCounterIDs(ids...)
	return _u
}

// RemoveWalletCounters removes "wallet_counters" edges to WalletCounter entities.
func (_u *KeyRootUpdateOne) RemoveWalletCounters(v ...*WalletCounter) *KeyRootUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWalletCounterIDs(ids...)
}

// Where appends a list predicates to the KeyRootUpdate builder.
func (_u *KeyRootUpdateOne) Where(ps ...predicate.KeyRoot) *KeyRootUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KeyRootUpdateOne) Select(field string, fields ...string) *KeyRootUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KeyRoot entity.
func (_u *KeyRootUpdateOne) Save(ctx context.Context) (*KeyRoot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeyRootUpdateOne) SaveX(ctx context.Context) *KeyRoot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KeyRootUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeyRootUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *KeyRootUpdateOne) sqlSave(ctx context.Context) (_node *KeyRoot, err error) {
	_spec := sqlgraph.NewUpdateSpec(keyroot.Table, keyroot.Columns, sqlgraph.NewFieldSpec(keyroot.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KeyRoot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, keyroot.FieldID)
		for _, f := range fields {
			if !keyroot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != keyroot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.WalletsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletsTable,
			Columns: []string{keyroot.WalletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWalletsIDs(); len(nodes) > 0 && !_u.mutation.WalletsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletsTable,
			Columns: []string{keyroot.WalletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletsTable,
			Columns: []string{keyroot.WalletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WalletCountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletCountersTable,
			Columns: []string{keyroot.WalletCountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(walletcounter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWalletCountersIDs(); len(nodes) > 0 && !_u.mutation.WalletCountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletCountersTable,
			Columns: []string{keyroot.WalletCountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(walletcounter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletCountersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keyroot.WalletCountersTable,
			Columns: []string{keyroot.WalletCountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(walletcounter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &KeyRoot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keyroot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
