// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rajabinekoo/sigryx/internal/ent/keyroot"
	"github.com/rajabinekoo/sigryx/internal/ent/predicate"
	"github.com/rajabinekoo/sigryx/internal/ent/wallet"
	"github.com/rajabinekoo/sigryx/internal/ent/walletcounter"
)

// KeyRootQuery is the builder for querying KeyRoot entities.
type KeyRootQuery struct {
	config
	ctx                *QueryContext
	order              []keyroot.OrderOption
	inters             []Interceptor
	predicates         []predicate.KeyRoot
	withWallets        *WalletQuery
	withWalletCounters *WalletCounterQuery
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the KeyRootQuery builder.
func (_q *KeyRootQuery) Where(ps ...predicate.KeyRoot) *KeyRootQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *KeyRootQuery) Limit(limit int) *KeyRootQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *KeyRootQuery) Offset(offset int) *KeyRootQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *KeyRootQuery) Unique(unique bool) *KeyRootQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *KeyRootQuery) Order(o ...keyroot.OrderOption) *KeyRootQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWallets chains the current query on the "wallets" edge.
func (_q *KeyRootQuery) QueryWallets() *WalletQuery {
	query := (&WalletClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(keyroot.Table, keyroot.FieldID, selector),
			sqlgraph.To(wallet.Table, wallet.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, keyroot.WalletsTable, keyroot.WalletsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWalletCounters chains the current query on the "wallet_counters" edge.
func (_q *KeyRootQuery) QueryWalletCounters() *WalletCounterQuery {
	query := (&WalletCounterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(keyroot.Table, keyroot.FieldID, selector),
			sqlgraph.To(walletcounter.Table, walletcounter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, keyroot.WalletCountersTable, keyroot.WalletCountersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first KeyRoot entity from the query.
// Returns a *NotFoundError when no KeyRoot was found.
func (_q *KeyRootQuery) First(ctx context.Context) (*KeyRoot, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{keyroot.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *KeyRootQuery) FirstX(ctx context.Context) *KeyRoot {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first KeyRoot ID from the query.
// Returns a *NotFoundError when no KeyRoot ID was found.
func (_q *KeyRootQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{keyroot.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *KeyRootQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single KeyRoot entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one KeyRoot entity is found.
// Returns a *NotFoundError when no KeyRoot entities are found.
func (_q *KeyRootQuery) Only(ctx context.Context) (*KeyRoot, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{keyroot.Label}
	default:
		return nil, &NotSingularError{keyroot.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *KeyRootQuery) OnlyX(ctx context.Context) *KeyRoot {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only KeyRoot ID in the query.
// Returns a *NotSingularError when more than one KeyRoot ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *KeyRootQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{keyroot.Label}
	default:
		err = &NotSingularError{keyroot.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *KeyRootQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of KeyRoots.
func (_q *KeyRootQuery) All(ctx context.Context) ([]*KeyRoot, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*KeyRoot, *KeyRootQuery]()
	return withInterceptors[[]*KeyRoot](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *KeyRootQuery) AllX(ctx context.Context) []*KeyRoot {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of KeyRoot IDs.
func (_q *KeyRootQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(keyroot.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *KeyRootQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *KeyRootQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*KeyRootQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *KeyRootQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *KeyRootQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *KeyRootQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the KeyRootQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *KeyRootQuery) Clone() *KeyRootQuery {
	if _q == nil {
		return nil
	}
	return &KeyRootQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]keyroot.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.KeyRoot{}, _q.predicates...),
		withWallets:        _q.withWallets.Clone(),
		withWalletCounters: _q.withWalletCounters.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWallets tells the query-builder to eager-load the nodes that are connected to
// the "wallets" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *KeyRootQuery) WithWallets(opts ...func(*WalletQuery)) *KeyRootQuery {
	query := (&WalletClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWallets = query
	return _q
}

// WithWalletCounters tells the query-builder to eager-load the nodes that are connected to
// the "wallet_counters" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *KeyRootQuery) WithWalletCounters(opts ...func(*WalletCounterQuery)) *KeyRootQuery {
	query := (&WalletCounterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWalletCounters = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DerivationScheme string `json:"derivation_scheme,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.KeyRoot.Query().
//		GroupBy(keyroot.FieldDerivationScheme).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *KeyRootQuery) GroupBy(field string, fields ...string) *KeyRootGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &KeyRootGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = keyroot.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DerivationScheme string `json:"derivation_scheme,omitempty"`
//	}
//
//	client.KeyRoot.Query().
//		Select(keyroot.FieldDerivationScheme).
//		Scan(ctx, &v)
func (_q *KeyRootQuery) Select(fields ...string) *KeyRootSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &KeyRootSelect{KeyRootQuery: _q}
	sbuild.label = keyroot.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a KeyRootSelect configured with the given aggregations.
func (_q *KeyRootQuery) Aggregate(fns ...AggregateFunc) *KeyRootSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *KeyRootQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !keyroot.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *KeyRootQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*KeyRoot, error) {
	var (
		nodes       = []*KeyRoot{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withWallets != nil,
			_q.withWalletCounters != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*KeyRoot).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &KeyRoot{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWallets; query != nil {
		if err := _q.loadWallets(ctx, query, nodes,
			func(n *KeyRoot) { n.Edges.Wallets = []*Wallet{} },
			func(n *KeyRoot, e *Wallet) { n.Edges.Wallets = append(n.Edges.Wallets, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWalletCounters; query != nil {
		if err := _q.loadWalletCounters(ctx, query, nodes,
			func(n *KeyRoot) { n.Edges.WalletCounters = []*WalletCounter{} },
			func(n *KeyRoot, e *WalletCounter) { n.Edges.WalletCounters = append(n.Edges.WalletCounters, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *KeyRootQuery) loadWallets(ctx context.Context, query *WalletQuery, nodes []*KeyRoot, init func(*KeyRoot), assign func(*KeyRoot, *Wallet)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*KeyRoot)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(wallet.FieldKeyRootID)
	}
	query.Where(predicate.Wallet(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(keyroot.WalletsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.KeyRootID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "key_root_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *KeyRootQuery) loadWalletCounters(ctx context.Context, query *WalletCounterQuery, nodes []*KeyRoot, init func(*KeyRoot), assign func(*KeyRoot, *WalletCounter)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*KeyRoot)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(walletcounter.FieldKeyRootID)
	}
	query.Where(predicate.WalletCounter(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(keyroot.WalletCountersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.KeyRootID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "key_root_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *KeyRootQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *KeyRootQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(keyroot.Table, keyroot.Columns, sqlgraph.NewFieldSpec(keyroot.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, keyroot.FieldID)
		for i := range fields {
			if fields[i] != keyroot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *KeyRootQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(keyroot.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = keyroot.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *KeyRootQuery) ForUpdate(opts ...sql.LockOption) *KeyRootQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *KeyRootQuery) ForShare(opts ...sql.LockOption) *KeyRootQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// KeyRootGroupBy is the group-by builder for KeyRoot entities.
type KeyRootGroupBy struct {
	selector
	build *KeyRootQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *KeyRootGroupBy) Aggregate(fns ...AggregateFunc) *KeyRootGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *KeyRootGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*KeyRootQuery, *KeyRootGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *KeyRootGroupBy) sqlScan(ctx context.Context, root *KeyRootQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// KeyRootSelect is the builder for selecting fields of KeyRoot entities.
type KeyRootSelect struct {
	*KeyRootQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *KeyRootSelect) Aggregate(fns ...AggregateFunc) *KeyRootSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *KeyRootSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*KeyRootQuery, *KeyRootSelect](ctx, _s.KeyRootQuery, _s, _s.inters, v)
}

func (_s *KeyRootSelect) sqlScan(ctx context.Context, root *KeyRootQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
