// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/rajabinekoo/sigryx/internal/ent/keyroot"
	"github.com/rajabinekoo/sigryx/internal/ent/schema"
	"github.com/rajabinekoo/sigryx/internal/ent/unsealkeyslot"
	"github.com/rajabinekoo/sigryx/internal/ent/wallet"
	"github.com/rajabinekoo/sigryx/internal/ent/walletcounter"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	keyrootFields := schema.KeyRoot{}.Fields()
	_ = keyrootFields
	// keyrootDescDerivationScheme is the schema descriptor for derivation_scheme field.
	keyrootDescDerivationScheme := keyrootFields[1].Descriptor()
	// keyroot.DerivationSchemeValidator is a validator for the "derivation_scheme" field. It is called by the builders before save.
	keyroot.DerivationSchemeValidator = keyrootDescDerivationScheme.Validators[0].(func(string) error)
	unsealkeyslotFields := schema.UnsealKeySlot{}.Fields()
	_ = unsealkeyslotFields
	// unsealkeyslotDescID is the schema descriptor for id field.
	unsealkeyslotDescID := unsealkeyslotFields[0].Descriptor()
	// unsealkeyslot.IDValidator is a validator for the "id" field. It is called by the builders before save.
	unsealkeyslot.IDValidator = unsealkeyslotDescID.Validators[0].(func(int) error)
	walletFields := schema.Wallet{}.Fields()
	_ = walletFields
	// walletDescUserID is the schema descriptor for user_id field.
	walletDescUserID := walletFields[2].Descriptor()
	// wallet.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	wallet.UserIDValidator = walletDescUserID.Validators[0].(func(string) error)
	// walletDescAdapter is the schema descriptor for adapter field.
	walletDescAdapter := walletFields[3].Descriptor()
	// wallet.AdapterValidator is a validator for the "adapter" field. It is called by the builders before save.
	wallet.AdapterValidator = walletDescAdapter.Validators[0].(func(string) error)
	// walletDescDerivationPath is the schema descriptor for derivation_path field.
	walletDescDerivationPath := walletFields[4].Descriptor()
	// wallet.DerivationPathValidator is a validator for the "derivation_path" field. It is called by the builders before save.
	wallet.DerivationPathValidator = walletDescDerivationPath.Validators[0].(func(string) error)
	// walletDescAddress is the schema descriptor for address field.
	walletDescAddress := walletFields[6].Descriptor()
	// wallet.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	wallet.AddressValidator = walletDescAddress.Validators[0].(func(string) error)
	walletcounterFields := schema.WalletCounter{}.Fields()
	_ = walletcounterFields
	// walletcounterDescAdapter is the schema descriptor for adapter field.
	walletcounterDescAdapter := walletcounterFields[1].Descriptor()
	// walletcounter.AdapterValidator is a validator for the "adapter" field. It is called by the builders before save.
	walletcounter.AdapterValidator = walletcounterDescAdapter.Validators[0].(func(string) error)
	// walletcounterDescNextIndex is the schema descriptor for next_index field.
	walletcounterDescNextIndex := walletcounterFields[2].Descriptor()
	// walletcounter.DefaultNextIndex holds the default value on creation for the next_index field.
	walletcounter.DefaultNextIndex = walletcounterDescNextIndex.Default.(int64)
	// walletcounter.NextIndexValidator is a validator for the "next_index" field. It is called by the builders before save.
	walletcounter.NextIndexValidator = func() func(int64) error {
		validators := walletcounterDescNextIndex.Validators
		fns := [...]func(int64) error{
			validators[0].(func(int64) error),
			validators[1].(func(int64) error),
		}
		return func(next_index int64) error {
			for _, fn := range fns {
				if err := fn(next_index); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
