// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rajabinekoo/sigryx/internal/ent/role"
	"github.com/rajabinekoo/sigryx/internal/ent/serviceaccount"
)

// ServiceAccount is the model entity for the ServiceAccount schema.
type ServiceAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// ClientSecretHash holds the value of the "client_secret_hash" field.
	ClientSecretHash []byte `json:"client_secret_hash,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID string `json:"role_id,omitempty"`
	// AllowedCidrs holds the value of the "allowed_cidrs" field.
	AllowedCidrs []string `json:"allowed_cidrs,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServiceAccountQuery when eager-loading is set.
	Edges        ServiceAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServiceAccountEdges holds the relations/edges for other nodes in the graph.
type ServiceAccountEdges struct {
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServiceAccountEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServiceAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serviceaccount.FieldClientSecretHash, serviceaccount.FieldAllowedCidrs:
			values[i] = new([]byte)
		case serviceaccount.FieldActive:
			values[i] = new(sql.NullBool)
		case serviceaccount.FieldID, serviceaccount.FieldName, serviceaccount.FieldClientID, serviceaccount.FieldRoleID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServiceAccount fields.
func (_m *ServiceAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serviceaccount.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case serviceaccount.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case serviceaccount.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case serviceaccount.FieldClientSecretHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field client_secret_hash", values[i])
			} else if value != nil {
				_m.ClientSecretHash = *value
			}
		case serviceaccount.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case serviceaccount.FieldRoleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = value.String
			}
		case serviceaccount.FieldAllowedCidrs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_cidrs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedCidrs); err != nil {
					return fmt.Errorf("unmarshal field allowed_cidrs: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServiceAccount.
// This includes values selected through modifiers, order, etc.
func (_m *ServiceAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the ServiceAccount entity.
func (_m *ServiceAccount) QueryRole() *RoleQuery {
	return NewServiceAccountClient(_m.config).QueryRole(_m)
}

// Update returns a builder for updating this ServiceAccount.
// Note that you need to call ServiceAccount.Unwrap() before calling this method if this ServiceAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServiceAccount) Update() *ServiceAccountUpdateOne {
	return NewServiceAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServiceAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServiceAccount) Unwrap() *ServiceAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServiceAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServiceAccount) String() string {
	var builder strings.Builder
	builder.WriteString("ServiceAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("client_secret_hash=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientSecretHash))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(_m.RoleID)
	builder.WriteString(", ")
	builder.WriteString("allowed_cidrs=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedCidrs))
	builder.WriteByte(')')
	return builder.String()
}

// ServiceAccounts is a parsable slice of ServiceAccount.
type ServiceAccounts []*ServiceAccount
