// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rajabinekoo/sigryx/internal/ent/role"
	"github.com/rajabinekoo/sigryx/internal/ent/serviceaccount"
)

// ServiceAccountCreate is the builder for creating a ServiceAccount entity.
type ServiceAccountCreate struct {
	config
	mutation *ServiceAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ServiceAccountCreate) SetName(v string) *ServiceAccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *ServiceAccountCreate) SetClientID(v string) *ServiceAccountCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_c *ServiceAccountCreate) SetClientSecretHash(v []byte) *ServiceAccountCreate {
	_c.mutation.SetClientSecretHash(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *ServiceAccountCreate) SetActive(v bool) *ServiceAccountCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *ServiceAccountCreate) SetNillableActive(v *bool) *ServiceAccountCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *ServiceAccountCreate) SetRoleID(v string) *ServiceAccountCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetAllowedCidrs sets the "allowed_cidrs" field.
func (_c *ServiceAccountCreate) SetAllowedCidrs(v []string) *ServiceAccountCreate {
	_c.mutation.SetAllowedCidrs(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ServiceAccountCreate) SetID(v string) *ServiceAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRole sets the "role" edge to the Role entity.
func (_c *ServiceAccountCreate) SetRole(v *Role) *ServiceAccountCreate {
	return _c.SetRoleID(v.ID)
}

// Mutation returns the ServiceAccountMutation object of the builder.
func (_c *ServiceAccountCreate) Mutation() *ServiceAccountMutation {
	return _c.mutation
}

// Save creates the ServiceAccount in the database.
func (_c *ServiceAccountCreate) Save(ctx context.Context) (*ServiceAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ServiceAccountCreate) SaveX(ctx context.Context) *ServiceAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ServiceAccountCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := serviceaccount.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.AllowedCidrs(); !ok {
		v := serviceaccount.DefaultAllowedCidrs
		_c.mutation.SetAllowedCidrs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ServiceAccountCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ServiceAccount.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := serviceaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ServiceAccount.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "ServiceAccount.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := serviceaccount.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "ServiceAccount.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientSecretHash(); !ok {
		return &ValidationError{Name: "client_secret_hash", err: errors.New(`ent: missing required field "ServiceAccount.client_secret_hash"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "ServiceAccount.active"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "ServiceAccount.role_id"`)}
	}
	if _, ok := _c.mutation.AllowedCidrs(); !ok {
		return &ValidationError{Name: "allowed_cidrs", err: errors.New(`ent: missing required field "ServiceAccount.allowed_cidrs"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "ServiceAccount.role"`)}
	}
	return nil
}

func (_c *ServiceAccountCreate) sqlSave(ctx context.Context) (*ServiceAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ServiceAccount.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ServiceAccountCreate) createSpec() (*ServiceAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(serviceaccount.Table, sqlgraph.NewFieldSpec(serviceaccount.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(serviceaccount.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(serviceaccount.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecretHash(); ok {
		_spec.SetField(serviceaccount.FieldClientSecretHash, field.TypeBytes, value)
		_node.ClientSecretHash = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(serviceaccount.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.AllowedCidrs(); ok {
		_spec.SetField(serviceaccount.FieldAllowedCidrs, field.TypeJSON, value)
		_node.AllowedCidrs = value
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serviceaccount.RoleTable,
			Columns: []string{serviceaccount.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ServiceAccount.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ServiceAccountUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ServiceAccountCreate) OnConflict(opts ...sql.ConflictOption) *ServiceAccountUpsertOne {
	_c.conflict = opts
	return &ServiceAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ServiceAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ServiceAccountCreate) OnConflictColumns(columns ...string) *ServiceAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ServiceAccountUpsertOne{
		create: _c,
	}
}

type (
	// ServiceAccountUpsertOne is the builder for "upsert"-ing
	//  one ServiceAccount node.
	ServiceAccountUpsertOne struct {
		create *ServiceAccountCreate
	}

	// ServiceAccountUpsert is the "OnConflict" setter.
	ServiceAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ServiceAccountUpsert) SetName(v string) *ServiceAccountUpsert {
	u.Set(serviceaccount.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ServiceAccountUpsert) UpdateName() *ServiceAccountUpsert {
	u.SetExcluded(serviceaccount.FieldName)
	return u
}

// SetClientID sets the "client_id" field.
func (u *ServiceAccountUpsert) SetClientID(v string) *ServiceAccountUpsert {
	u.Set(serviceaccount.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ServiceAccountUpsert) UpdateClientID() *ServiceAccountUpsert {
	u.SetExcluded(serviceaccount.FieldClientID)
	return u
}

// SetActive sets the "active" field.
func (u *ServiceAccountUpsert) SetActive(v bool) *ServiceAccountUpsert {
	u.Set(serviceaccount.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *ServiceAccountUpsert) UpdateActive() *ServiceAccountUpsert {
	u.SetExcluded(serviceaccount.FieldActive)
	return u
}

// SetRoleID sets the "role_id" field.
func (u *ServiceAccountUpsert) SetRoleID(v string) *ServiceAccountUpsert {
	u.Set(serviceaccount.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *ServiceAccountUpsert) UpdateRoleID() *ServiceAccountUpsert {
	u.SetExcluded(serviceaccount.FieldRoleID)
	return u
}

// SetAllowedCidrs sets the "allowed_cidrs" field.
func (u *ServiceAccountUpsert) SetAllowedCidrs(v []string) *ServiceAccountUpsert {
	u.Set(serviceaccount.FieldAllowedCidrs, v)
	return u
}

// UpdateAllowedCidrs sets the "allowed_cidrs" field to the value that was provided on create.
func (u *ServiceAccountUpsert) UpdateAllowedCidrs() *ServiceAccountUpsert {
	u.SetExcluded(serviceaccount.FieldAllowedCidrs)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ServiceAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(serviceaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ServiceAccountUpsertOne) UpdateNewValues() *ServiceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(serviceaccount.FieldID)
		}
		if _, exists := u.create.mutation.ClientSecretHash(); exists {
			s.SetIgnore(serviceaccount.FieldClientSecretHash)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ServiceAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ServiceAccountUpsertOne) Ignore() *ServiceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ServiceAccountUpsertOne) DoNothing() *ServiceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ServiceAccountCreate.OnConflict
// documentation for more info.
func (u *ServiceAccountUpsertOne) Update(set func(*ServiceAccountUpsert)) *ServiceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ServiceAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ServiceAccountUpsertOne) SetName(v string) *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ServiceAccountUpsertOne) UpdateName() *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateName()
	})
}

// SetClientID sets the "client_id" field.
func (u *ServiceAccountUpsertOne) SetClientID(v string) *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ServiceAccountUpsertOne) UpdateClientID() *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateClientID()
	})
}

// SetActive sets the "active" field.
func (u *ServiceAccountUpsertOne) SetActive(v bool) *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *ServiceAccountUpsertOne) UpdateActive() *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateActive()
	})
}

// SetRoleID sets the "role_id" field.
func (u *ServiceAccountUpsertOne) SetRoleID(v string) *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *ServiceAccountUpsertOne) UpdateRoleID() *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateRoleID()
	})
}

// SetAllowedCidrs sets the "allowed_cidrs" field.
func (u *ServiceAccountUpsertOne) SetAllowedCidrs(v []string) *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetAllowedCidrs(v)
	})
}

// UpdateAllowedCidrs sets the "allowed_cidrs" field to the value that was provided on create.
func (u *ServiceAccountUpsertOne) UpdateAllowedCidrs() *ServiceAccountUpsertOne {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateAllowedCidrs()
	})
}

// Exec executes the query.
func (u *ServiceAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ServiceAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ServiceAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ServiceAccountUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ServiceAccountUpsertOne.ID is not supported by MySQL driver. Use ServiceAccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ServiceAccountUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ServiceAccountCreateBulk is the builder for creating many ServiceAccount entities in bulk.
type ServiceAccountCreateBulk struct {
	config
	err      error
	builders []*ServiceAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the ServiceAccount entities in the database.
func (_c *ServiceAccountCreateBulk) Save(ctx context.Context) ([]*ServiceAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ServiceAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ServiceAccountCreateBulk) SaveX(ctx context.Context) []*ServiceAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ServiceAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ServiceAccountUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ServiceAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *ServiceAccountUpsertBulk {
	_c.conflict = opts
	return &ServiceAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ServiceAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ServiceAccountCreateBulk) OnConflictColumns(columns ...string) *ServiceAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ServiceAccountUpsertBulk{
		create: _c,
	}
}

// ServiceAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of ServiceAccount nodes.
type ServiceAccountUpsertBulk struct {
	create *ServiceAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ServiceAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(serviceaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ServiceAccountUpsertBulk) UpdateNewValues() *ServiceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(serviceaccount.FieldID)
			}
			if _, exists := b.mutation.ClientSecretHash(); exists {
				s.SetIgnore(serviceaccount.FieldClientSecretHash)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ServiceAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ServiceAccountUpsertBulk) Ignore() *ServiceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ServiceAccountUpsertBulk) DoNothing() *ServiceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ServiceAccountCreateBulk.OnConflict
// documentation for more info.
func (u *ServiceAccountUpsertBulk) Update(set func(*ServiceAccountUpsert)) *ServiceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ServiceAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ServiceAccountUpsertBulk) SetName(v string) *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ServiceAccountUpsertBulk) UpdateName() *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateName()
	})
}

// SetClientID sets the "client_id" field.
func (u *ServiceAccountUpsertBulk) SetClientID(v string) *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ServiceAccountUpsertBulk) UpdateClientID() *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateClientID()
	})
}

// SetActive sets the "active" field.
func (u *ServiceAccountUpsertBulk) SetActive(v bool) *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *ServiceAccountUpsertBulk) UpdateActive() *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateActive()
	})
}

// SetRoleID sets the "role_id" field.
func (u *ServiceAccountUpsertBulk) SetRoleID(v string) *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *ServiceAccountUpsertBulk) UpdateRoleID() *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateRoleID()
	})
}

// SetAllowedCidrs sets the "allowed_cidrs" field.
func (u *ServiceAccountUpsertBulk) SetAllowedCidrs(v []string) *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.SetAllowedCidrs(v)
	})
}

// UpdateAllowedCidrs sets the "allowed_cidrs" field to the value that was provided on create.
func (u *ServiceAccountUpsertBulk) UpdateAllowedCidrs() *ServiceAccountUpsertBulk {
	return u.Update(func(s *ServiceAccountUpsert) {
		s.UpdateAllowedCidrs()
	})
}

// Exec executes the query.
func (u *ServiceAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ServiceAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ServiceAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ServiceAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
