// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rajabinekoo/sigryx/internal/ent/predicate"
	"github.com/rajabinekoo/sigryx/internal/ent/signingrecord"
)

// SigningRecordUpdate is the builder for updating SigningRecord entities.
type SigningRecordUpdate struct {
	config
	hooks    []Hook
	mutation *SigningRecordMutation
}

// Where appends a list predicates to the SigningRecordUpdate builder.
func (_u *SigningRecordUpdate) Where(ps ...predicate.SigningRecord) *SigningRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the SigningRecordMutation object of the builder.
func (_u *SigningRecordUpdate) Mutation() *SigningRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SigningRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SigningRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SigningRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SigningRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SigningRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(signingrecord.Table, signingrecord.Columns, sqlgraph.NewFieldSpec(signingrecord.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signingrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SigningRecordUpdateOne is the builder for updating a single SigningRecord entity.
type SigningRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SigningRecordMutation
}

// Mutation returns the SigningRecordMutation object of the builder.
func (_u *SigningRecordUpdateOne) Mutation() *SigningRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the SigningRecordUpdate builder.
func (_u *SigningRecordUpdateOne) Where(ps ...predicate.SigningRecord) *SigningRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SigningRecordUpdateOne) Select(field string, fields ...string) *SigningRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SigningRecord entity.
func (_u *SigningRecordUpdateOne) Save(ctx context.Context) (*SigningRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SigningRecordUpdateOne) SaveX(ctx context.Context) *SigningRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SigningRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SigningRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SigningRecordUpdateOne) sqlSave(ctx context.Context) (_node *SigningRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(signingrecord.Table, signingrecord.Columns, sqlgraph.NewFieldSpec(signingrecord.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SigningRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signingrecord.FieldID)
		for _, f := range fields {
			if !signingrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != signingrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &SigningRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signingrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
