// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rajabinekoo/sigryx/internal/ent/unsealkeyslot"
)

// UnsealKeySlot is the model entity for the UnsealKeySlot schema.
type UnsealKeySlot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// WrappedKey holds the value of the "wrapped_key" field.
	WrappedKey []byte `json:"wrapped_key,omitempty"`
	// ServerKeyMaterial holds the value of the "server_key_material" field.
	ServerKeyMaterial []byte `json:"server_key_material,omitempty"`
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UnsealKeySlot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case unsealkeyslot.FieldWrappedKey, unsealkeyslot.FieldServerKeyMaterial:
			values[i] = new([]byte)
		case unsealkeyslot.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UnsealKeySlot fields.
func (_m *UnsealKeySlot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case unsealkeyslot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case unsealkeyslot.FieldWrappedKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field wrapped_key", values[i])
			} else if value != nil {
				_m.WrappedKey = *value
			}
		case unsealkeyslot.FieldServerKeyMaterial:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field server_key_material", values[i])
			} else if value != nil {
				_m.ServerKeyMaterial = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UnsealKeySlot.
// This includes values selected through modifiers, order, etc.
func (_m *UnsealKeySlot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UnsealKeySlot.
// Note that you need to call UnsealKeySlot.Unwrap() before calling this method if this UnsealKeySlot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UnsealKeySlot) Update() *UnsealKeySlotUpdateOne {
	return NewUnsealKeySlotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UnsealKeySlot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UnsealKeySlot) Unwrap() *UnsealKeySlot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UnsealKeySlot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UnsealKeySlot) String() string {
	var builder strings.Builder
	builder.WriteString("UnsealKeySlot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("wrapped_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.WrappedKey))
	builder.WriteString(", ")
	builder.WriteString("server_key_material=")
	builder.WriteString(fmt.Sprintf("%v", _m.ServerKeyMaterial))
	builder.WriteByte(')')
	return builder.String()
}

// UnsealKeySlots is a parsable slice of UnsealKeySlot.
type UnsealKeySlots []*UnsealKeySlot
