// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rajabinekoo/sigryx/internal/ent/predicate"
	"github.com/rajabinekoo/sigryx/internal/ent/unsealkeyslot"
)

// UnsealKeySlotUpdate is the builder for updating UnsealKeySlot entities.
type UnsealKeySlotUpdate struct {
	config
	hooks    []Hook
	mutation *UnsealKeySlotMutation
}

// Where appends a list predicates to the UnsealKeySlotUpdate builder.
func (_u *UnsealKeySlotUpdate) Where(ps ...predicate.UnsealKeySlot) *UnsealKeySlotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the UnsealKeySlotMutation object of the builder.
func (_u *UnsealKeySlotUpdate) Mutation() *UnsealKeySlotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UnsealKeySlotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnsealKeySlotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UnsealKeySlotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnsealKeySlotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UnsealKeySlotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(unsealkeyslot.Table, unsealkeyslot.Columns, sqlgraph.NewFieldSpec(unsealkeyslot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unsealkeyslot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UnsealKeySlotUpdateOne is the builder for updating a single UnsealKeySlot entity.
type UnsealKeySlotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UnsealKeySlotMutation
}

// Mutation returns the UnsealKeySlotMutation object of the builder.
func (_u *UnsealKeySlotUpdateOne) Mutation() *UnsealKeySlotMutation {
	return _u.mutation
}

// Where appends a list predicates to the UnsealKeySlotUpdate builder.
func (_u *UnsealKeySlotUpdateOne) Where(ps ...predicate.UnsealKeySlot) *UnsealKeySlotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UnsealKeySlotUpdateOne) Select(field string, fields ...string) *UnsealKeySlotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UnsealKeySlot entity.
func (_u *UnsealKeySlotUpdateOne) Save(ctx context.Context) (*UnsealKeySlot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnsealKeySlotUpdateOne) SaveX(ctx context.Context) *UnsealKeySlot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UnsealKeySlotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnsealKeySlotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UnsealKeySlotUpdateOne) sqlSave(ctx context.Context) (_node *UnsealKeySlot, err error) {
	_spec := sqlgraph.NewUpdateSpec(unsealkeyslot.Table, unsealkeyslot.Columns, sqlgraph.NewFieldSpec(unsealkeyslot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UnsealKeySlot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unsealkeyslot.FieldID)
		for _, f := range fields {
			if !unsealkeyslot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != unsealkeyslot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &UnsealKeySlot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unsealkeyslot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
