// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rajabinekoo/sigryx/internal/ent/unsealkeyslot"
)

// UnsealKeySlotCreate is the builder for creating a UnsealKeySlot entity.
type UnsealKeySlotCreate struct {
	config
	mutation *UnsealKeySlotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetWrappedKey sets the "wrapped_key" field.
func (_c *UnsealKeySlotCreate) SetWrappedKey(v []byte) *UnsealKeySlotCreate {
	_c.mutation.SetWrappedKey(v)
	return _c
}

// SetServerKeyMaterial sets the "server_key_material" field.
func (_c *UnsealKeySlotCreate) SetServerKeyMaterial(v []byte) *UnsealKeySlotCreate {
	_c.mutation.SetServerKeyMaterial(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UnsealKeySlotCreate) SetID(v int) *UnsealKeySlotCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UnsealKeySlotMutation object of the builder.
func (_c *UnsealKeySlotCreate) Mutation() *UnsealKeySlotMutation {
	return _c.mutation
}

// Save creates the UnsealKeySlot in the database.
func (_c *UnsealKeySlotCreate) Save(ctx context.Context) (*UnsealKeySlot, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UnsealKeySlotCreate) SaveX(ctx context.Context) *UnsealKeySlot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnsealKeySlotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnsealKeySlotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UnsealKeySlotCreate) check() error {
	if _, ok := _c.mutation.WrappedKey(); !ok {
		return &ValidationError{Name: "wrapped_key", err: errors.New(`ent: missing required field "UnsealKeySlot.wrapped_key"`)}
	}
	if _, ok := _c.mutation.ServerKeyMaterial(); !ok {
		return &ValidationError{Name: "server_key_material", err: errors.New(`ent: missing required field "UnsealKeySlot.server_key_material"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := unsealkeyslot.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "UnsealKeySlot.id": %w`, err)}
		}
	}
	return nil
}

func (_c *UnsealKeySlotCreate) sqlSave(ctx context.Context) (*UnsealKeySlot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UnsealKeySlotCreate) createSpec() (*UnsealKeySlot, *sqlgraph.CreateSpec) {
	var (
		_node = &UnsealKeySlot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(unsealkeyslot.Table, sqlgraph.NewFieldSpec(unsealkeyslot.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.WrappedKey(); ok {
		_spec.SetField(unsealkeyslot.FieldWrappedKey, field.TypeBytes, value)
		_node.WrappedKey = value
	}
	if value, ok := _c.mutation.ServerKeyMaterial(); ok {
		_spec.SetField(unsealkeyslot.FieldServerKeyMaterial, field.TypeBytes, value)
		_node.ServerKeyMaterial = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UnsealKeySlot.Create().
//		SetWrappedKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnsealKeySlotUpsert) {
//			SetWrappedKey(v+v).
//		}).
//		Exec(ctx)
func (_c *UnsealKeySlotCreate) OnConflict(opts ...sql.ConflictOption) *UnsealKeySlotUpsertOne {
	_c.conflict = opts
	return &UnsealKeySlotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UnsealKeySlot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnsealKeySlotCreate) OnConflictColumns(columns ...string) *UnsealKeySlotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnsealKeySlotUpsertOne{
		create: _c,
	}
}

type (
	// UnsealKeySlotUpsertOne is the builder for "upsert"-ing
	//  one UnsealKeySlot node.
	UnsealKeySlotUpsertOne struct {
		create *UnsealKeySlotCreate
	}

	// UnsealKeySlotUpsert is the "OnConflict" setter.
	UnsealKeySlotUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UnsealKeySlot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unsealkeyslot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnsealKeySlotUpsertOne) UpdateNewValues() *UnsealKeySlotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(unsealkeyslot.FieldID)
		}
		if _, exists := u.create.mutation.WrappedKey(); exists {
			s.SetIgnore(unsealkeyslot.FieldWrappedKey)
		}
		if _, exists := u.create.mutation.ServerKeyMaterial(); exists {
			s.SetIgnore(unsealkeyslot.FieldServerKeyMaterial)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UnsealKeySlot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UnsealKeySlotUpsertOne) Ignore() *UnsealKeySlotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnsealKeySlotUpsertOne) DoNothing() *UnsealKeySlotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnsealKeySlotCreate.OnConflict
// documentation for more info.
func (u *UnsealKeySlotUpsertOne) Update(set func(*UnsealKeySlotUpsert)) *UnsealKeySlotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnsealKeySlotUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *UnsealKeySlotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnsealKeySlotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnsealKeySlotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UnsealKeySlotUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UnsealKeySlotUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UnsealKeySlotCreateBulk is the builder for creating many UnsealKeySlot entities in bulk.
type UnsealKeySlotCreateBulk struct {
	config
	err      error
	builders []*UnsealKeySlotCreate
	conflict []sql.ConflictOption
}

// Save creates the UnsealKeySlot entities in the database.
func (_c *UnsealKeySlotCreateBulk) Save(ctx context.Context) ([]*UnsealKeySlot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UnsealKeySlot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UnsealKeySlotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UnsealKeySlotCreateBulk) SaveX(ctx context.Context) []*UnsealKeySlot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnsealKeySlotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnsealKeySlotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UnsealKeySlot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnsealKeySlotUpsert) {
//			SetWrappedKey(v+v).
//		}).
//		Exec(ctx)
func (_c *UnsealKeySlotCreateBulk) OnConflict(opts ...sql.ConflictOption) *UnsealKeySlotUpsertBulk {
	_c.conflict = opts
	return &UnsealKeySlotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UnsealKeySlot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnsealKeySlotCreateBulk) OnConflictColumns(columns ...string) *UnsealKeySlotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnsealKeySlotUpsertBulk{
		create: _c,
	}
}

// UnsealKeySlotUpsertBulk is the builder for "upsert"-ing
// a bulk of UnsealKeySlot nodes.
type UnsealKeySlotUpsertBulk struct {
	create *UnsealKeySlotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UnsealKeySlot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unsealkeyslot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnsealKeySlotUpsertBulk) UpdateNewValues() *UnsealKeySlotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(unsealkeyslot.FieldID)
			}
			if _, exists := b.mutation.WrappedKey(); exists {
				s.SetIgnore(unsealkeyslot.FieldWrappedKey)
			}
			if _, exists := b.mutation.ServerKeyMaterial(); exists {
				s.SetIgnore(unsealkeyslot.FieldServerKeyMaterial)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UnsealKeySlot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UnsealKeySlotUpsertBulk) Ignore() *UnsealKeySlotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnsealKeySlotUpsertBulk) DoNothing() *UnsealKeySlotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnsealKeySlotCreateBulk.OnConflict
// documentation for more info.
func (u *UnsealKeySlotUpsertBulk) Update(set func(*UnsealKeySlotUpsert)) *UnsealKeySlotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnsealKeySlotUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *UnsealKeySlotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UnsealKeySlotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnsealKeySlotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnsealKeySlotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
