// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rajabinekoo/sigryx/internal/ent/keyroot"
	"github.com/rajabinekoo/sigryx/internal/ent/walletcounter"
)

// WalletCounter is the model entity for the WalletCounter schema.
type WalletCounter struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// KeyRootID holds the value of the "key_root_id" field.
	KeyRootID string `json:"key_root_id,omitempty"`
	// Adapter holds the value of the "adapter" field.
	Adapter string `json:"adapter,omitempty"`
	// NextIndex holds the value of the "next_index" field.
	NextIndex int64 `json:"next_index,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WalletCounterQuery when eager-loading is set.
	Edges        WalletCounterEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WalletCounterEdges holds the relations/edges for other nodes in the graph.
type WalletCounterEdges struct {
	// KeyRoot holds the value of the key_root edge.
	KeyRoot *KeyRoot `json:"key_root,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// KeyRootOrErr returns the KeyRoot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WalletCounterEdges) KeyRootOrErr() (*KeyRoot, error) {
	if e.KeyRoot != nil {
		return e.KeyRoot, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: keyroot.Label}
	}
	return nil, &NotLoadedError{edge: "key_root"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WalletCounter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case walletcounter.FieldID, walletcounter.FieldNextIndex:
			values[i] = new(sql.NullInt64)
		case walletcounter.FieldKeyRootID, walletcounter.FieldAdapter:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WalletCounter fields.
func (_m *WalletCounter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case walletcounter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case walletcounter.FieldKeyRootID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_root_id", values[i])
			} else if value.Valid {
				_m.KeyRootID = value.String
			}
		case walletcounter.FieldAdapter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field adapter", values[i])
			} else if value.Valid {
				_m.Adapter = value.String
			}
		case walletcounter.FieldNextIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field next_index", values[i])
			} else if value.Valid {
				_m.NextIndex = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WalletCounter.
// This includes values selected through modifiers, order, etc.
func (_m *WalletCounter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryKeyRoot queries the "key_root" edge of the WalletCounter entity.
func (_m *WalletCounter) QueryKeyRoot() *KeyRootQuery {
	return NewWalletCounterClient(_m.config).QueryKeyRoot(_m)
}

// Update returns a builder for updating this WalletCounter.
// Note that you need to call WalletCounter.Unwrap() before calling this method if this WalletCounter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WalletCounter) Update() *WalletCounterUpdateOne {
	return NewWalletCounterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WalletCounter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WalletCounter) Unwrap() *WalletCounter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WalletCounter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WalletCounter) String() string {
	var builder strings.Builder
	builder.WriteString("WalletCounter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key_root_id=")
	builder.WriteString(_m.KeyRootID)
	builder.WriteString(", ")
	builder.WriteString("adapter=")
	builder.WriteString(_m.Adapter)
	builder.WriteString(", ")
	builder.WriteString("next_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextIndex))
	builder.WriteByte(')')
	return builder.String()
}

// WalletCounters is a parsable slice of WalletCounter.
type WalletCounters []*WalletCounter
