// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rajabinekoo/sigryx/internal/ent/keyroot"
	"github.com/rajabinekoo/sigryx/internal/ent/wallet"
)

// Wallet is the model entity for the Wallet schema.
type Wallet struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// KeyRootID holds the value of the "key_root_id" field.
	KeyRootID string `json:"key_root_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Adapter holds the value of the "adapter" field.
	Adapter string `json:"adapter,omitempty"`
	// DerivationPath holds the value of the "derivation_path" field.
	DerivationPath string `json:"derivation_path,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey []byte `json:"public_key,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WalletQuery when eager-loading is set.
	Edges        WalletEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WalletEdges holds the relations/edges for other nodes in the graph.
type WalletEdges struct {
	// KeyRoot holds the value of the key_root edge.
	KeyRoot *KeyRoot `json:"key_root,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// KeyRootOrErr returns the KeyRoot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WalletEdges) KeyRootOrErr() (*KeyRoot, error) {
	if e.KeyRoot != nil {
		return e.KeyRoot, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: keyroot.Label}
	}
	return nil, &NotLoadedError{edge: "key_root"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Wallet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wallet.FieldPublicKey:
			values[i] = new([]byte)
		case wallet.FieldID, wallet.FieldKeyRootID, wallet.FieldUserID, wallet.FieldAdapter, wallet.FieldDerivationPath, wallet.FieldAddress:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Wallet fields.
func (_m *Wallet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wallet.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case wallet.FieldKeyRootID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_root_id", values[i])
			} else if value.Valid {
				_m.KeyRootID = value.String
			}
		case wallet.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case wallet.FieldAdapter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field adapter", values[i])
			} else if value.Valid {
				_m.Adapter = value.String
			}
		case wallet.FieldDerivationPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field derivation_path", values[i])
			} else if value.Valid {
				_m.DerivationPath = value.String
			}
		case wallet.FieldPublicKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value != nil {
				_m.PublicKey = *value
			}
		case wallet.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Wallet.
// This includes values selected through modifiers, order, etc.
func (_m *Wallet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryKeyRoot queries the "key_root" edge of the Wallet entity.
func (_m *Wallet) QueryKeyRoot() *KeyRootQuery {
	return NewWalletClient(_m.config).QueryKeyRoot(_m)
}

// Update returns a builder for updating this Wallet.
// Note that you need to call Wallet.Unwrap() before calling this method if this Wallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Wallet) Update() *WalletUpdateOne {
	return NewWalletClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Wallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Wallet) Unwrap() *Wallet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Wallet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Wallet) String() string {
	var builder strings.Builder
	builder.WriteString("Wallet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key_root_id=")
	builder.WriteString(_m.KeyRootID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("adapter=")
	builder.WriteString(_m.Adapter)
	builder.WriteString(", ")
	builder.WriteString("derivation_path=")
	builder.WriteString(_m.DerivationPath)
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicKey))
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteByte(')')
	return builder.String()
}

// Wallets is a parsable slice of Wallet.
type Wallets []*Wallet
