// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// KeyRoot is the predicate function for keyroot builders.
type KeyRoot func(*sql.Selector)

// UnsealKeySlot is the predicate function for unsealkeyslot builders.
type UnsealKeySlot func(*sql.Selector)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)

// WalletCounter is the predicate function for walletcounter builders.
type WalletCounter func(*sql.Selector)
