-- Create "key_roots" table
CREATE TABLE "public"."key_roots" (
  "id" uuid NOT NULL,
  "derivation_scheme" character varying NOT NULL,
  "sealed_seed" bytea NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "key_root_sealed_seed_not_empty" CHECK (octet_length(sealed_seed) > 0)
);
-- Create "unseal_key_slots" table
CREATE TABLE "public"."unseal_key_slots" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "wrapped_key" bytea NOT NULL,
  "server_key_material" bytea NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "unseal_server_key_material_size" CHECK (octet_length(server_key_material) = 32),
  CONSTRAINT "unseal_wrapped_key_not_empty" CHECK (octet_length(wrapped_key) > 0)
);
-- Create index "unsealkeyslot_wrapped_key" to table: "unseal_key_slots"
CREATE UNIQUE INDEX "unsealkeyslot_wrapped_key" ON "public"."unseal_key_slots" ("wrapped_key");
-- Create "wallet_counters" table
CREATE TABLE "public"."wallet_counters" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "adapter" character varying NOT NULL,
  "next_index" bigint NOT NULL DEFAULT 0,
  "key_root_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "wallet_counters_key_roots_wallet_counters" FOREIGN KEY ("key_root_id") REFERENCES "public"."key_roots" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "wallet_counter_index_range" CHECK ((next_index >= 0) AND (next_index <= '2147483648'::bigint))
);
-- Create index "walletcounter_key_root_id_adapter" to table: "wallet_counters"
CREATE UNIQUE INDEX "walletcounter_key_root_id_adapter" ON "public"."wallet_counters" ("key_root_id", "adapter");
-- Create "wallets" table
CREATE TABLE "public"."wallets" (
  "id" uuid NOT NULL,
  "adapter" character varying NOT NULL,
  "derivation_path" character varying NOT NULL,
  "public_key" bytea NOT NULL,
  "address" character varying NOT NULL,
  "key_root_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "wallets_key_roots_wallets" FOREIGN KEY ("key_root_id") REFERENCES "public"."key_roots" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "wallet_public_key_not_empty" CHECK (octet_length(public_key) > 0)
);
-- Create index "wallet_adapter_address" to table: "wallets"
CREATE UNIQUE INDEX "wallet_adapter_address" ON "public"."wallets" ("adapter", "address");
-- Create index "wallet_key_root_id_adapter_derivation_path" to table: "wallets"
CREATE UNIQUE INDEX "wallet_key_root_id_adapter_derivation_path" ON "public"."wallets" ("key_root_id", "adapter", "derivation_path");
