// Code generated by ent, DO NOT EDIT.

package serviceaccount

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rajabinekoo/sigryx/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldName, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldClientID, v))
}

// ClientSecretHash applies equality check predicate on the "client_secret_hash" field. It's identical to ClientSecretHashEQ.
func ClientSecretHash(v []byte) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldClientSecretHash, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldActive, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldRoleID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldContainsFold(FieldName, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretHashEQ applies the EQ predicate on the "client_secret_hash" field.
func ClientSecretHashEQ(v []byte) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldClientSecretHash, v))
}

// ClientSecretHashNEQ applies the NEQ predicate on the "client_secret_hash" field.
func ClientSecretHashNEQ(v []byte) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNEQ(FieldClientSecretHash, v))
}

// ClientSecretHashIn applies the In predicate on the "client_secret_hash" field.
func ClientSecretHashIn(vs ...[]byte) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashNotIn applies the NotIn predicate on the "client_secret_hash" field.
func ClientSecretHashNotIn(vs ...[]byte) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNotIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashGT applies the GT predicate on the "client_secret_hash" field.
func ClientSecretHashGT(v []byte) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGT(FieldClientSecretHash, v))
}

// ClientSecretHashGTE applies the GTE predicate on the "client_secret_hash" field.
func ClientSecretHashGTE(v []byte) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGTE(FieldClientSecretHash, v))
}

// ClientSecretHashLT applies the LT predicate on the "client_secret_hash" field.
func ClientSecretHashLT(v []byte) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLT(FieldClientSecretHash, v))
}

// ClientSecretHashLTE applies the LTE predicate on the "client_secret_hash" field.
func ClientSecretHashLTE(v []byte) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLTE(FieldClientSecretHash, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNEQ(FieldActive, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDContains applies the Contains predicate on the "role_id" field.
func RoleIDContains(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldContains(FieldRoleID, v))
}

// RoleIDHasPrefix applies the HasPrefix predicate on the "role_id" field.
func RoleIDHasPrefix(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldHasPrefix(FieldRoleID, v))
}

// RoleIDHasSuffix applies the HasSuffix predicate on the "role_id" field.
func RoleIDHasSuffix(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldHasSuffix(FieldRoleID, v))
}

// RoleIDEqualFold applies the EqualFold predicate on the "role_id" field.
func RoleIDEqualFold(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldEqualFold(FieldRoleID, v))
}

// RoleIDContainsFold applies the ContainsFold predicate on the "role_id" field.
func RoleIDContainsFold(v string) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.FieldContainsFold(FieldRoleID, v))
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.ServiceAccount {
	return predicate.ServiceAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.ServiceAccount {
	return predicate.ServiceAccount(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServiceAccount) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServiceAccount) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServiceAccount) predicate.ServiceAccount {
	return predicate.ServiceAccount(sql.NotPredicates(p))
}
