// Code generated by ent, DO NOT EDIT.

package wallet

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the wallet type in the database.
	Label = "wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKeyRootID holds the string denoting the key_root_id field in the database.
	FieldKeyRootID = "key_root_id"
	// FieldAdapter holds the string denoting the adapter field in the database.
	FieldAdapter = "adapter"
	// FieldDerivationPath holds the string denoting the derivation_path field in the database.
	FieldDerivationPath = "derivation_path"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// EdgeKeyRoot holds the string denoting the key_root edge name in mutations.
	EdgeKeyRoot = "key_root"
	// Table holds the table name of the wallet in the database.
	Table = "wallets"
	// KeyRootTable is the table that holds the key_root relation/edge.
	KeyRootTable = "wallets"
	// KeyRootInverseTable is the table name for the KeyRoot entity.
	// It exists in this package in order to avoid circular dependency with the "keyroot" package.
	KeyRootInverseTable = "key_roots"
	// KeyRootColumn is the table column denoting the key_root relation/edge.
	KeyRootColumn = "key_root_id"
)

// Columns holds all SQL columns for wallet fields.
var Columns = []string{
	FieldID,
	FieldKeyRootID,
	FieldAdapter,
	FieldDerivationPath,
	FieldPublicKey,
	FieldAddress,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AdapterValidator is a validator for the "adapter" field. It is called by the builders before save.
	AdapterValidator func(string) error
	// DerivationPathValidator is a validator for the "derivation_path" field. It is called by the builders before save.
	DerivationPathValidator func(string) error
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
)

// OrderOption defines the ordering options for the Wallet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKeyRootID orders the results by the key_root_id field.
func ByKeyRootID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyRootID, opts...).ToFunc()
}

// ByAdapter orders the results by the adapter field.
func ByAdapter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdapter, opts...).ToFunc()
}

// ByDerivationPath orders the results by the derivation_path field.
func ByDerivationPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDerivationPath, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByKeyRootField orders the results by key_root field.
func ByKeyRootField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKeyRootStep(), sql.OrderByField(field, opts...))
	}
}
func newKeyRootStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KeyRootInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, KeyRootTable, KeyRootColumn),
	)
}
