// Code generated by ent, DO NOT EDIT.

package wallet

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rajabinekoo/sigryx/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContainsFold(FieldID, id))
}

// KeyRootID applies equality check predicate on the "key_root_id" field. It's identical to KeyRootIDEQ.
func KeyRootID(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldKeyRootID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldUserID, v))
}

// Adapter applies equality check predicate on the "adapter" field. It's identical to AdapterEQ.
func Adapter(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldAdapter, v))
}

// DerivationPath applies equality check predicate on the "derivation_path" field. It's identical to DerivationPathEQ.
func DerivationPath(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldDerivationPath, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldPublicKey, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldAddress, v))
}

// KeyRootIDEQ applies the EQ predicate on the "key_root_id" field.
func KeyRootIDEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldKeyRootID, v))
}

// KeyRootIDNEQ applies the NEQ predicate on the "key_root_id" field.
func KeyRootIDNEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldKeyRootID, v))
}

// KeyRootIDIn applies the In predicate on the "key_root_id" field.
func KeyRootIDIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldKeyRootID, vs...))
}

// KeyRootIDNotIn applies the NotIn predicate on the "key_root_id" field.
func KeyRootIDNotIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldKeyRootID, vs...))
}

// KeyRootIDGT applies the GT predicate on the "key_root_id" field.
func KeyRootIDGT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldKeyRootID, v))
}

// KeyRootIDGTE applies the GTE predicate on the "key_root_id" field.
func KeyRootIDGTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldKeyRootID, v))
}

// KeyRootIDLT applies the LT predicate on the "key_root_id" field.
func KeyRootIDLT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldKeyRootID, v))
}

// KeyRootIDLTE applies the LTE predicate on the "key_root_id" field.
func KeyRootIDLTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldKeyRootID, v))
}

// KeyRootIDContains applies the Contains predicate on the "key_root_id" field.
func KeyRootIDContains(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContains(FieldKeyRootID, v))
}

// KeyRootIDHasPrefix applies the HasPrefix predicate on the "key_root_id" field.
func KeyRootIDHasPrefix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasPrefix(FieldKeyRootID, v))
}

// KeyRootIDHasSuffix applies the HasSuffix predicate on the "key_root_id" field.
func KeyRootIDHasSuffix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasSuffix(FieldKeyRootID, v))
}

// KeyRootIDEqualFold applies the EqualFold predicate on the "key_root_id" field.
func KeyRootIDEqualFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEqualFold(FieldKeyRootID, v))
}

// KeyRootIDContainsFold applies the ContainsFold predicate on the "key_root_id" field.
func KeyRootIDContainsFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContainsFold(FieldKeyRootID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContainsFold(FieldUserID, v))
}

// AdapterEQ applies the EQ predicate on the "adapter" field.
func AdapterEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldAdapter, v))
}

// AdapterNEQ applies the NEQ predicate on the "adapter" field.
func AdapterNEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldAdapter, v))
}

// AdapterIn applies the In predicate on the "adapter" field.
func AdapterIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldAdapter, vs...))
}

// AdapterNotIn applies the NotIn predicate on the "adapter" field.
func AdapterNotIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldAdapter, vs...))
}

// AdapterGT applies the GT predicate on the "adapter" field.
func AdapterGT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldAdapter, v))
}

// AdapterGTE applies the GTE predicate on the "adapter" field.
func AdapterGTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldAdapter, v))
}

// AdapterLT applies the LT predicate on the "adapter" field.
func AdapterLT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldAdapter, v))
}

// AdapterLTE applies the LTE predicate on the "adapter" field.
func AdapterLTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldAdapter, v))
}

// AdapterContains applies the Contains predicate on the "adapter" field.
func AdapterContains(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContains(FieldAdapter, v))
}

// AdapterHasPrefix applies the HasPrefix predicate on the "adapter" field.
func AdapterHasPrefix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasPrefix(FieldAdapter, v))
}

// AdapterHasSuffix applies the HasSuffix predicate on the "adapter" field.
func AdapterHasSuffix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasSuffix(FieldAdapter, v))
}

// AdapterEqualFold applies the EqualFold predicate on the "adapter" field.
func AdapterEqualFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEqualFold(FieldAdapter, v))
}

// AdapterContainsFold applies the ContainsFold predicate on the "adapter" field.
func AdapterContainsFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContainsFold(FieldAdapter, v))
}

// DerivationPathEQ applies the EQ predicate on the "derivation_path" field.
func DerivationPathEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldDerivationPath, v))
}

// DerivationPathNEQ applies the NEQ predicate on the "derivation_path" field.
func DerivationPathNEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldDerivationPath, v))
}

// DerivationPathIn applies the In predicate on the "derivation_path" field.
func DerivationPathIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldDerivationPath, vs...))
}

// DerivationPathNotIn applies the NotIn predicate on the "derivation_path" field.
func DerivationPathNotIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldDerivationPath, vs...))
}

// DerivationPathGT applies the GT predicate on the "derivation_path" field.
func DerivationPathGT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldDerivationPath, v))
}

// DerivationPathGTE applies the GTE predicate on the "derivation_path" field.
func DerivationPathGTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldDerivationPath, v))
}

// DerivationPathLT applies the LT predicate on the "derivation_path" field.
func DerivationPathLT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldDerivationPath, v))
}

// DerivationPathLTE applies the LTE predicate on the "derivation_path" field.
func DerivationPathLTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldDerivationPath, v))
}

// DerivationPathContains applies the Contains predicate on the "derivation_path" field.
func DerivationPathContains(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContains(FieldDerivationPath, v))
}

// DerivationPathHasPrefix applies the HasPrefix predicate on the "derivation_path" field.
func DerivationPathHasPrefix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasPrefix(FieldDerivationPath, v))
}

// DerivationPathHasSuffix applies the HasSuffix predicate on the "derivation_path" field.
func DerivationPathHasSuffix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasSuffix(FieldDerivationPath, v))
}

// DerivationPathEqualFold applies the EqualFold predicate on the "derivation_path" field.
func DerivationPathEqualFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEqualFold(FieldDerivationPath, v))
}

// DerivationPathContainsFold applies the ContainsFold predicate on the "derivation_path" field.
func DerivationPathContainsFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContainsFold(FieldDerivationPath, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...[]byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...[]byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldPublicKey, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContainsFold(FieldAddress, v))
}

// HasKeyRoot applies the HasEdge predicate on the "key_root" edge.
func HasKeyRoot() predicate.Wallet {
	return predicate.Wallet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, KeyRootTable, KeyRootColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeyRootWith applies the HasEdge predicate on the "key_root" edge with a given conditions (other predicates).
func HasKeyRootWith(preds ...predicate.KeyRoot) predicate.Wallet {
	return predicate.Wallet(func(s *sql.Selector) {
		step := newKeyRootStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Wallet) predicate.Wallet {
	return predicate.Wallet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Wallet) predicate.Wallet {
	return predicate.Wallet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Wallet) predicate.Wallet {
	return predicate.Wallet(sql.NotPredicates(p))
}
